### ISSUE TITLE
Add a default page name

### ISSUE THREAD

**Issue by solarmist** [rabbibotton/clog#106]
In Safari on macOS, the text box is nearly invisible, so I'd like to suggest adding a default title for new pages.

`(let ((new-page  (create-form-element (main app) :text :value "New Page"))`

https://github.com/rabbibotton/clog/blob/74e38ba1ab56a3e292682f4eefeec1f711e6f505/demos/04-demo.lisp#L62

**Comment by rabbibotton** [comment]
Done. Thanks!
