### ISSUE TITLE
substantive typo in Common Lisp - "The Tutorial" Part 2

### ISSUE THREAD

**Issue by sgoldkin** [rabbibotton/clog#120]
In CL tutorial part 2, you say:

"In emacs execute C-x C-f and type a file name say like hello.lisp. 
The .lisp extension is most often used. 
We can not enter our program in to our file:
(print "hello")
Save the file C-x C-s"

Clearly, you meant to say:  "We can now enter our program into our file"

This could be very confusing for beginners.

**Comment by rabbibotton** [comment]
Corrected, thanks!!
