### ISSUE TITLE
Using Google Docs for the tutorial?

### ISSUE THREAD

**Issue by pronoiac** [rabbibotton/clog#124]
*Greetings from [Hacker News!](https://news.ycombinator.com/item?id=31178737)* 

Out of curiosity, why are you using [Google Docs for the tutorial posts](https://github.com/rabbibotton/clog/blob/main/LEARN.md)? It's surprising, a bit distracting, and the mobile view of code might be lacking. 

I'd include them in the repo: save the docs as docx files, then use pandoc to turn those into Markdown files. Let me know if you could use help!

**Comment by rabbibotton** [comment]
cool :)

My plan is to migrate it to mark down, on next iteration will work on it.
