### ISSUE TITLE
Working time tracking tool using CLOG (programming noob)

### ISSUE THREAD

**Issue by hapst3r** [rabbibotton/clog#130]
Hej,

I recently wrote on reddit, asking for a way to find out the screen resolution.

Trying to give a bit more context, maybe it will be easier to understand what I am trying to achieve, as I still struggle to formulate in proper terms what I require for my program.

I am currently trying to design and program a user interface which gives users (my coworkers and me) the possibility to input working time data, especially regarding the spread of working time over two types of categories: (1) pedagogical work/preparation of that work/administration (2) a specification of what was chosen for (1). Using this, I want to gather data in order to pressure my superiors into either accepting that we have way more administrative chores then they see, or changing something about this problem. Because it is a problem when we are supposed to have 20% of our working time in administration and I find myself since more than one year having around 40%.

The user interface mainly revolves around two sections which could be dubbed "Input" and "Output". 

**Input**
- In the Input section, the users are supposed to enter their data: date, working time span (e.g. 10-18:00), the place where you work (I work in two different places) and the distribution of working time ( (1) from above). This data is written to an array slot and stored locally. 
- I want to offer two options for Input: one that is quick and requires said data for an entire day, and one which is exhaustive and requires the data for each time span within the working day (e.g. 10:00-11:00, pedagogical work, homework support). This is supposed to help with another administrative chore where we have to evaluate, at the end of the year, how we expended our working time. 
- On the GUI side, I consider this a bit special: while the "quick" method requires only few text fields (they ideally should have labels above them), the "exhaustive" method should feature a "+" sign at the end of each new row to create a new row right below (I normally have something between 4 and 8 slots per day, but the users' mileage may vary).

**Output**
- In the Output section, I want to show the aggregated data to the user. The program reads the array and aggregates matching entries (I already wrote a working prototype, will probably have to adapt to gui). On the one hand, I want the show the user, for the current {month,quarter,year}, how much working time has been expended in which category. I'm not set on the details of this, as depending on whether the user customarily chooses "quick" or "exhaustive" Input, the Output could get very big and messy (I always use "exhaustive" and employ around 20 different specification categories).
- On the other hand, I want to allow for PDF export which can be much more verbose and show the distribution for each month or quarter, and for the entire year. As you might have guessed by now, I hope to use this as a tool to put pressure on my superiors to do something about the amount of administration that is part of my (and my colleagues') everyday life as pedagogical professionals. Because every minute that is spent on administration is a minute that cannot be expended working with children (our job), and currently it feels like it's pretty much the other way around.

So, I guess this should do as an explanation for a start. The code already present is public and can be found over at gitlab: https://gitlab.com/hapster/azvdoc . The repo is a bit messy because I am still learning how to use it and how to manage a repo. Most of the work happens in the files "construct-transform", "date", "day", "time" and "save-restore". I am also in the process of experimenting how to structure my program, since it is the first "real" program I write (excercise programs don't count in my opinion). 

I hope I am not taking too much of your time with this issue where I'm basically asking for spoonfeeding and already want to thank you for the offer to discuss (here or over on reddit doesn't make a difference for me). Have a good day and thanks for your contribution to the community with clog, the resources you offer (tutorials etc) and your willingness to help people.

Have a good day :)

**Comment by rabbibotton** [comment]
Let me know how you are doing on that :)

**Comment by hapst3r** [comment]
Hej :)

I am currently following the CLOG builder tutorials as posted on reddit. Overall, they are very enjoyable. However, progress is slow, since I trip here and there.

- One thing that might be worth a footnote: I spent the better part of yesterday's programming time trying to figure out why "adding" the login to the page didn't work for me. It turns out that clog doesn't like element names with whitespace because it treats them as two entities (I guess): While renaming the login's elements, I renamed DIV-4 to "TEXT ALIGNMENT" and then had the error "TEXT ALIGNMENT" pop up when trying to re-load the package. Since "TEXT ALIGNMENT" was also the name of a property, it was rather confusing to debug. Another lesson for my programming noob self: don't choose element names that are also property names ;-)
- Now, I am still stuck with adding the LOGIN panel created in the first steps to the page. While I was able to figure out, I am kind of out of my wits with this one. I tried following the code provided in the tutorial apart from the fact that you now mostly use ON-NEW-WINDOW as function to be called by init functions such as START-APP (I followed that convention, CLOG builder also does by now). However, I get the error that the CREATE-MY-LOGIN function could not be found. Find below the code of ON-NEW-WINDOW as I currently have it. Directly below, find the code from the tutorial.

`(defun on-new-window (body)
  ;; Add the clog-web look and feel
  (clog-web-initialize body)
  ;; Use the panel-box-layout to center horizontally
  ;; and vertically our div on the screen.
  (let* ((layout (create-panel-box-layout body)))
    (center-children (center-panel layout))
    (create-my-login (center-panel layout))))`

`(defun start-my-chat (body)
  ;; Add the clog-web look and feel
  (clog-web:clog-web-initialize body)
  ;; Use the panel-box-layout to center horizontally
  ;; and vertically our my-login panel on the screen.
  (let* ((layout (create-panel-box-layout body)))
    (center-children (center-panel layout))
    (create-my-login (center-panel layout))))`

**Comment by hapst3r** [comment]
Hej,

I have now arrived at tutorial 4 and can see why you suggested it ;-) 

**Problem 1**

I'm starting to get to grips with the way the clog builder works. However, about halfway through the tutorial (just defined CET-ON-NEW and CET-ON-EDIT), I realise that the interaction between the program and the database doesn't work properly. I get this error:

> Could not open sqlite3 database /home/hapster/programming/.site-data/programming/clog/clos-contact/clos-contact.db
> Code CANTOPEN: no message.


At first, I thought that this is because of the way in which I created the database. I first created the database tables using the program sqlitebrowser. Even though the variables were displayed a bit differently -- e.g. "varname" VARTYPE --, the database can be opened using the clog-db-admin tool.

After running into said problem above, I figured that maybe the different display of the variables in the database might be the problem and created the database anew, this time using the approach described in the tutorial: opening clog-db-admin tool, choosing a non-existent file, then three times "execute non-query", inputting the statements in the tutorial. As a result, the database now looks exactly like on the image provided. However, the error persists.

Do you have an idea where I'd have to look for debugging the issue? The only help I can think of is the Backtrace:
```
 0: (SQLITE:SQLITE-ERROR :CANTOPEN ("Could not open sqlite3 database ~A" "/home/hapster/programming/.site-data/programming/clog/clos-contact/clos-contact.db") :STATEMENT NIL :DB-HANDLE NIL :SQL-TEXT NIL)
 1: ((:METHOD INITIALIZE-INSTANCE :AFTER (SQLITE:SQLITE-HANDLE)) #<SQLITE:SQLITE-HANDLE {10063C0473}> :DATABASE-PATH "/home/hapster/programming/.site-data/programming/clog/clos-contact/clos-contact.db") [..
 2: ((LAMBDA (SB-PCL::|.P0.|)) #<unavailable argument>)
 3: (SQLITE:CONNECT "/home/hapster/programming/.site-data/programming/clog/clos-contact/clos-contact.db" :BUSY-TIMEOUT NIL)
 4: ((:METHOD DBI.DRIVER:MAKE-CONNECTION (DBD.SQLITE3:DBD-SQLITE3)) #<unused argument> :DATABASE-NAME "/home/hapster/programming/.site-data/programming/clog/clos-contact/clos-contact.db" :BUSY-TIMEOUT NIL..
 5: (CLOS-CONTACT::CREATE-CONFIG-EVENT-TYPES #<CLOG:CLOG-ELEMENT {1006396473}> :HIDDEN NIL :CLASS NIL :HTML-ID NIL :AUTO-PLACE T)
 6: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
```

**Question**
In the beginning of the tutorial, everything happens in CLOG builder: new windows are created, properties are defined etc. Thus, whenever a change has happened in CLOG builder, I could save to a CLOG file and then render to a LISP file.

However, later on, this way of working changes: function definitions are input in emacs, in the same file that CLOG builder used to operate on (if I understand correctly). 

After working on the LISP file manually, I cannot use the RENDER functionality in CLOG builder because this will overwrite the contents of the LISP file.

What is the correct way to work side-by-side in CLOG builder and emacs?

I am asking because for some time I had a DIV centering the elements (that's what I'd seen in an earlier tutorial, can't recall which one). Then, when I first ran into the error above, I decided to remove it (less deviation from the tutorials equals less sources of error, I thought). I did remove it in CLOG builder, but now I don't know how to make changes appear in the LISP file in emacs.

I mean there is a way to do that: copying the manually written functions, RENDER the CLOG file to a LISP file, paste the manually written functions. But this seems unintuitive, is there a better way to do this?

Thanks, have a good time :)

**Comment by rabbibotton** [comment]
<<Typo
In Step 7 of the CLOG Builder Tutorial 4, a database listbox is created. The related table name is event_types. However, insofar as event_types relates to the tables created in the sqlite database, it has to be event_type (not event_typeS).>>
Fixed- Thanks!!

**Comment by rabbibotton** [comment]
<<However, later on, this way of working changes: function definitions are input in emacs, in the same file that CLOG builder used to operate on (if I understand correctly).

After working on the LISP file manually, I cannot use the RENDER functionality in CLOG builder because this will overwrite the contents of the LISP file.>>

You do modify files that were created with the Application Templates, but should never be directly editing any of the lisp files generated by the builder. So if you add an event for example you would not be adding that it the generated files but other files in your application.

So in the builder you are entering in the control events the names of functions from your code.

**Comment by rabbibotton** [comment]
question 3 - will help to see how you are going about things in code for me. So end me that zip and I'll see about some steps to make this easier. I really appreciate you taking the time to work thought the tutorials and try them and get stuck :( and write. It really helps me to make the whole process understandable and easier for all my goal. So we end up with a product that is super easy to create apps with.

**Comment by rabbibotton** [comment]
BTW in case didn't know - the completed tutorial is also at - https://github.com/rabbibotton/clos-contact

**Comment by hapst3r** [comment]
Okay, first things first: thanks for the headsup regarding the completed clos-contact tutorial. It shows quite clearly the point you are making: no manual code in builder-created files. Maybe the problem leading to my **Question 2** is associated with it. It would even make sense, since whenever I added code to the `config-event-types.lisp` file, I afterwards compiled either the specific function or the entire buffer (while you seem to use `C-M-x`, I tend to use `C-c C-c` or `C-x C-e`, dunno if there's an important difference). If there's a mechanism for the builder to recognise the differences between a rendered file and the same file where a definition has changed, it makes sense for the builder to complain. Will report back on the issue.

But I believe in either case, the tutorial is a bit misleading: while you advise me here to not put code in RNDR'ed files, it's literally the first sentence of Step 8 ("So in our config-event-types.lisp file let's add our three events as place filters"). Maybe there's also a misunderstanding on my part, but I read this as "Put you code in this file".
I think it generally makes sense to put a kind of warning or reminder somewhere (e.g. on the github page itself, or the documentation of the builder, or as a footnote to tutorial 4 since I feel like it was not so much of an issue in earlier tutorials). If there is such a reminder and I have failed to notice it, please pardon my ignorance.

As before, I will continue editing. Shall I be unable to fix **Question 2** by putting my code elsewhere, I will upload a zip file of the project in here.

**Comment by rabbibotton** [comment]
Thank you so much, all of this gives me many perspectives in how to improve everything for those approaching it the first time. My ultimate goal is to make everything stupid simple so a pointy hared boss man could even do much of the programming work.

**Comment by hapst3r** [comment]
**Providing "style guideline" in tutorial**
In Tutorial 1 you mentioned that using a "div" to align several elements - div in "relative" positioning, the (text) elements either "static" or "absolute" - is often times what you want. I am trying to adopt this habit because I find it a nightmare to manually adjust the elements and still look "right". Wouldn't it make sense to suggest this use further along in the other tutorials or to show that you are using this in later tutorials? Because it seemed kinda off to me that while your GUI windows always look kinda lit, you never apply the suggestion you made yourself.

********************

**Comment by aykaramba** [comment]
I would recommed that you consider the tutorials as version 1 and that additional revisions might be appropriate to improve them.  Having read all of the written tutorials my self, they also skip a bunch of information and assume you have learned from previous tutorials to just get the project done.

What this means is that, in my reading, we would benefit by NOT changing the existing tutorials much at all, only fixing grammar, spelling and maybe a bit wording here or there.  The reason for that recommendation is that all tutorials have a target audience, no tutorial can ever satisfy all audiences because everyone is at a different part of the learning curve and therefore the tutorials are perfect for their intended audience: slightly more than basic to kind of intermediate audience that is enthusiastic and is willing to look things up.

I would also, therefore, suggest that we put together a set of guides and best practices.  For example, the one that I wanted to write was the one that deals with the use of a main relative dive and the child divs as static or absolute as necessary.  I am testing out creating of templates that look modern right now in order to figure out how to write this tutorial in a way that is somewhat based on trying to make real things.

The other tutorial that needs writing is how to read the documentation and translate that into code.  I am starting to get it but as I am not a full time Lisp programmer I am still guessing.  This should be straight forward in terms of explanation the bulk of the work being done to provide examples for each item in the documentation.

Then, I would like to build some template libraries and so forth so that people can take a look and see how they are built and improve them.

Your suggestion is fine but there are better ways to accomplish what you are suggesting other than changing the main tutorials.  I thank my lucky stars we have all of this documentation, tutorials and so forth.

**Comment by rabbibotton** [comment]
How you doing :) Making progress? any issues?

**Comment by hapst3r** [comment]
Hej david, thanks for keeping in touch! 

The last two weeks I was busy with other stuff and it is only now that I get back at it (finally!). If I find more stuff / run into more problems, I will update this post.

**Comment by rabbibotton** [comment]
You set-on-click for a button that says ready to get the form contents, you then just access the form contents directly (text-value some-control) there are more ways but that is a good starting place.

**Comment by rabbibotton** [comment]
https://github.com/rabbibotton/clog/blob/main/tutorial/17-tutorial.lisp

**Comment by hapst3r** [comment]
I started to design my GUI and ran into problems not related to my earlier question. Thanks a bunch for the link!

**How to set $ELEMENT (table) borders in Builder**
If I understand correctly, it is possible to set both borders and outlines for clog elements via an elements' builder settings. The settings for both _outline_ and _borders_ consists of three elements: size, type and color.

Now, I've tried to change those settings to something like (for border): `5px medium rgb(0, 0, 0`. So far, with Builder, the values would change as soon as I leave the value cell of said element. However, for border and outline, nothing happens. 

Changing the element focus to another element and back to the element with border, I realised that somehow Builder didn't take the values but has reverted to the default values.

**Comment by hapst3r** [comment]
### Why does table column alignment stop working as soon as I start using form inputs?
I am starting to experiment with the table elements to which IIUC corresponds HTMLs variants. Thus, a table consists of those elements:

- table
- table head/table body
- table row for each row in head/body
- table heading for each desired column in head row
- table column for each desired column in body row

So far, when I worked with only headings and columns, everything went fine. The column dividers (how to make them visible!?) would adjust to the size of the inserted element so that the overall formatting does not get screwed.

When I added a first form input, this still worked, the column size was adjusted accordingly. However, as soon as I added a second form input in one row, this mechanism stopped working. Also, it seemed like with the second form input added, the correspondence ONE ELEMENT-ONE COLUMN has been broken, because both form inputs appeared in the first column.

Why is this, and is there a possibility to change that?

### How to make font bold in Builder?
I am trying to make the text of a label bold. How do I do that? I have seen the font properties slot and experimented with it but have been unable to get what I wanted.

### How to insert a linebreak in a tooltip?
I discovered that it is possible to use placeholder text and tooltips to supply more information in one window and I gotta say I love it.

So I started creating tooltips in places where I deem it important. However, I don't see the possibility to insert linebreaks. Guessing I might have to input a HTML command (because many things in CLOG are) I tried `<br>` in the tooltip value area but without success. 

Is this possible, and if so, how?

### Date-format (quick, will edit)
I want to know if it is possible to change the way that date is represented. I am still experimenting with a Preview function that shows input before submitting it. And since I am a program targetting a german-speaking audience, I would like date to be represented as it is input (I am working with oldies as well ;-)). Currently, I input DD-MM-YYYY but receive YYYY-MM-DD. How to change?

As title says, this is quickly written down, I will do my research and update accordingly.

**Comment by rabbibotton** [comment]
<<Why does table column alignment stop working as soon as I start using form inputs?>>
I speak code better :)

<<How to make font bold in Builder?>>
1. (best way) Add the word bold to start of the font property "bold 15px / 22.5px Verdana, sans-serif"
2. Scroll down to the last property say in a label and you can add <b>..</b> around your label's text. (when you save the clog file and reload it you will see the bold tags are added as controls)

<<How to change the date format settings?>>
The format you get/set is always yyyy-mm-dd but the format the the user sees is always based on his local set on the machine or in the browser. There are ways to override "local"s but not a good idea and not sure if privacy will allow anymore.

<<Is it possible to generate CLOG elements "on the spot" using a button?>>
The beauty of CLOG is you can always do anything. Just create an on-click handler and use create-* to create what you want.

I don't really understand the rest, perhaps a code sample.

**Comment by rabbibotton** [comment]
making progress?

**Comment by hapst3r** [comment]
**Table-stuff**
I don't know how `static` and `relative` positioning differ from one another programmatically, but using `relative` for the table allowed me to build the kind of GUI window I wanted.

**Linebreak in tooltip**
So when I make a label, it has a `tooltip` slot. When I insert a linebreak in this tooltip, the two lines separated by line-break are collated to one another.

However, I'd love to have a hover-over label that HAS line-breaks. I guess I will then have to use control-events, right?

**Comment by rabbibotton** [comment]
Relative means to treat the item as static - but let you position it as absolute. It is key to allowing a control to be used in flex-box and other layouts. Usually I recommend when making controls to use relative as the layout of an outer div around the control. https://www.reddit.com/r/Common_Lisp/comments/w4zwm3/common_lisp_repl_style_dev_visually_with_clog/

**Comment by rabbibotton** [comment]
making progress?

**Comment by hapst3r** [comment]
hej,

again, I much appreciate that you don't just forget about this project, even after these many months.

I currently don't work on the project since it is tied to work and after an accident-induced wrist injury that will take a good few months to heal I don't work. Also because of the wrist injury I can't type nor program properly (one-handed).

If you would like to close the issue, that's completely fine by me. I can also close it.

However, if you don't mind too much, I'll open a new issue as soon as I get back to work and stumble across a problem I deem related to clog.

In the meantime, I will read Practical Common Lisp, I hope that afterwards my journey becomes a bit easier.

Have a good time, good fellow :)

**Comment by rabbibotton** [comment]
Hope you are doing well! I am going to close the issue but feel free to open another or still ask here.
