### ISSUE TITLE
Last commit was a breaking change.

### ISSUE THREAD

**Issue by sabracrolleton** [rabbibotton/clog#145]
After the last commit I now have an extra line ') ') ') at the top of a gui body and it broke various bits of things in my app under development. Rolling clog back to 13a09b2101d8b11d5645c6aa5654883358ae6518 fixed it. Have to get to sleep but will try to figure out what might have happened tomorrow.

**Comment by sabracrolleton** [comment]
I am also seeing it in demo 3.

**Comment by rabbibotton** [comment]
Very strange the only changes in coder are in this commit - https://github.com/rabbibotton/clog/commit/e43afc3d9eaabb1ff637ac048c355c3021a093ae

I am not seeing it, and can't see anything in the code (although I haven't slept in 36 hours).

Let me know what you see.
