### ISSUE TITLE
Change static-root path

### ISSUE THREAD

**Issue by timoteipalade** [rabbibotton/clog#147]
Hi! This project is really cool! You put a lot of love into it, and it shows at every step. 🥇 

My issue is the following. I want to change the `static-root` path. Here is what I have tried so far, which does not work:

``` Lisp
(defpackage #:playground
  (:use #:cl #:clog))

(in-package :playground)

(defun on-new-window (body) 
  "On-new-window handler."
  (set-on-load-script
   (html-document body)
   (lambda (obj data)
     (js-execute body "console.log('Hi')"))
   :one-time t)
  (load-script (html-document body) "plotly-2.12.1.min.js")
  (let ((plot-div (create-div body :html-id "plot")))
    (setf (attribute plot-div "style") "width:600px;height:250px;"))
  (js-execute body "Plotly.newPlot( document.getElementById('plot'), [{ x: [1, 2, 3, 4, 5], y: [1, 2, 4, 8, 16] }], {margin: { t: 0 } } );")
  (js-execute body "console.log('Hi');"))


(defun start-playground ()
  "Start tutorial."        
  (initialize
   #'on-new-window
   :static-root #P"/Users/me/Documents/Developer/Lisp/CandlesAndSticks/static-files/")
  (open-browser))
```

**Comment by rabbibotton** [comment]
Any time you change the static path you have to clog:shutdown and then clog:initialize again. Otherwise if that path exists looks ok to me. Let me know if that works

**Comment by timoteipalade** [comment]
It worked! 🚀  The path changed:

<img width="687" alt="Screenshot 2022-06-19 at 19 58 07" src="https://user-images.githubusercontent.com/25011107/174492089-191dd2b7-9538-424c-a01a-d2f372930bad.png">

But I ran into another head scratcher. I copied the files under `clog/static-files` to my `static-files` folder. It is complaining that it cannot load jQuery, which is really weird, since it exists. Tried `clog:shutdown` and then initialize again. 

Here is what I see in the console: 
<img width="858" alt="Screenshot 2022-06-19 at 20 01 17" src="https://user-images.githubusercontent.com/25011107/174492226-f9165c2f-5e9a-48c2-9752-b595f7b40cd5.png">

Somehow only `boot.js` gets loaded 🤔 :

<img width="855" alt="Screenshot 2022-06-19 at 20 02 17" src="https://user-images.githubusercontent.com/25011107/174492257-41670d00-96d4-4c65-8fd3-2ede4611412c.png">

**Comment by rabbibotton** [comment]
By default if boot.js is missing it uses a compiled version.
You can see if you have access to jQuery by typing http://127.0.0.1:8080/js/jquery.min.js

Btw you can do the following:
(ql:quickload :clog/tools)
(clog-tools:clog-new-app)

to use a template to setup a new project. You may find that easier.

**Comment by timoteipalade** [comment]
Thanks! 

I found the issue. Forward slash was missing at the end of my path: 

OLD: `#P"/Users/paladetimotei/Documents/Developer/Lisp/CandlesAndSticks/static-files`
NEW: `#P"/Users/paladetimotei/Documents/Developer/Lisp/CandlesAndSticks/static-files/` 

🤯  😆

**Comment by rabbibotton** [comment]
Awsome :)
