### ISSUE TITLE
create-pre ?

### ISSUE THREAD

**Issue by sabracrolleton** [rabbibotton/clog#154]
Any reason why there is no create-pre function?

**Comment by sabracrolleton** [comment]
Thank you. While I will not try to give you a compelling reason to add those as individual cases, can I ask that the list of section-types be referenced in the manual?

**Comment by rabbibotton** [comment]
hmm didn't realize not picked up by mgx-pax, I'll play around with seeing how to get the list to show or just add it to the docstring. Thanks!

**Comment by rabbibotton** [comment]
I added them to the documentation strings. Thanks!!
