### ISSUE TITLE
Mixed tabs and spaces

### ISSUE THREAD

**Issue by simendsjo** [rabbibotton/clog#168]
I notice there are some mixed tabs and spaces in the source, making parts a bit difficult to read. But it might seem unintentional? In such case, a detab would be nice.

![image](https://user-images.githubusercontent.com/351519/178802583-b398339c-0d91-46da-881e-c465e78b6a97.png)

**Comment by rabbibotton** [comment]
I will take a look at pull request soon, a bit busy for next day. Main thing is I need a reliable way to get emacs not to put the tabs back.

**Comment by rabbibotton** [comment]
I am not ignoring you :) I have my focus on a new tutorial (Lisp custom controls) and then can spend time on this.

**Comment by rabbibotton** [comment]
I have updated the files and hopefully set up a way to keep things with out tabs. Thanks!!
