### ISSUE TITLE
CLOG-TOOLS:CLOG-BUILDER, `Custom Html`, and Bootstrap5

### ISSUE THREAD

**Issue by johndebord** [rabbibotton/clog#178]
Using CLOG-TOOLS:CLOG-BUILDER I have two snippets of html being dropped-in by `Custom Html`:
```html
<div>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</div>
```
```html
<div>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      Dropdown button
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li><a class="dropdown-item" href="#">Action</a></li>
      <li><a class="dropdown-item" href="#">Another action</a></li>
      <li><a class="dropdown-item" href="#">Something else here</a></li>
    </ul>
  </div>
</div>
```
In the Clog Builder panel everything looks ok:
![sc0](https://user-images.githubusercontent.com/35586806/179837266-1320838e-dd65-451e-b6eb-7483bda88761.png)

But when I test it out something seems to break:
![sc1](https://user-images.githubusercontent.com/35586806/179837393-4b9b8cf8-f974-45c8-b6eb-a35243f22dd6.png)

**Comment by rabbibotton** [comment]
You will have issues using boot strap in a panel. Do instead Builder -> New Basic HTML Page and the you can paste in each snippet one at a time or use the New Bootstrap Page that uses the bootstrap boot page that comes with CLOG (either works ok) then just paste the second snippet.

If still having issues let me know, you are on windows? Let me know if this is still not working. I'll try when home to try this on a windows laptop as I expect may be something related to the line endings.

**Comment by johndebord** [comment]
Currently using Linux. And yeah, I soon discovered `New Bootstrap Page` right after encountering this issue. I'll give that a go, thanks

**Comment by rabbibotton** [comment]
I assume at this point all ok with this? If not reopen.
