### ISSUE TITLE
Was missing a page on cliki.net

### ISSUE THREAD

**Issue by informatimago** [rabbibotton/clog#18]
I created a page for CLOG on http://cliki.net/CLOG but it's very rudimentary.

**Comment by rabbibotton** [comment]
How do I get an account, been trying for a month as the signup doesn't work asked a few times on irc, discourse etc :(

**Comment by rabbibotton** [comment]
oh and of course thank you!

**Comment by rabbibotton** [comment]
Somehow got in now :) Thanks
