### ISSUE TITLE
CLOG repl fails on macOS 12.4 with SBCL 2.2.6 and Chrome 103.0.5060.114

### ISSUE THREAD

**Issue by mikelevins** [rabbibotton/clog#180]
On macOS 12.4 Intel, with Chrome 103.0.5060.114 set as the default web browser, do the following:

1. Start sbcl from GNU Emacs using SLIME v2.27
2. quickload :clog
3. eval (clog:clog-repl)

Result:

- Chrome poses an empty browser window; see the body of the HTML document below:

<!doctype HTML>
<HTML>
  <HEAD>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="/js/jquery.min.js" type="text/javascript"></script>
    <script src="/js/boot.js" type="text/javascript"></script>
    <noscript><%= (@ meta) %></noscript>
  </HEAD>
  <BODY>
    <noscript><%= (@ body) %></noscript>
  </BODY>
<noscript>Your browser must support JavaScript and be HTML 5 compilant to see this site.</noscript>
</HTML>

- Reloading the page yields the following error message in the SLIME repl:

Hunchentoot server is started.
Listening on 0.0.0.0:8080.
HTTP listening on    : 0.0.0.0:8080
HTML root            : /Users/mikel/quicklisp/dists/quicklisp/software/clog-20220707-git/static-files/
Long poll first      : no
Boot function added  : no
Boot html source use : compiled version, when no file
Boot js source use   : compiled version
Boot file for path / : /debug.html
Use clog-user:*body* to access the clog-repl window.
NIL
New connection id - 1 - #<SERVER {100CA81183}>
[2022-07-19 15:47:50 [ERROR]] Error while processing connection: Condition USOCKET:CONNECTION-ABORTED-ERROR was signalled.
New connection id - 3 - #<SERVER {100E0AA2F3}>

**Comment by aykaramba** [comment]
Just tested this on 10.15.7 with the following results:

'(eval (clog:clog-repl))'  ==> works

'(in-package clog-user) (clog-repl)' ==> works

CAVEATE: The terminal won't let got of the session and I have to Ctrl-C and exit out of the debugger to be able to start creating divs and such.

Just a datapoint, hopefully it is useful.

**Comment by rabbibotton** [comment]
@mikelevins those are all expected results.

1. Try (clog:create-div clog-user:*body* :content "hello") and you will see it is working. CLOG is rendering through the browser not assembling an HTML document (although you can dump the rendered page as html).
2. The meta data if not set in initialize (and no real reason to do so on a gui) will have some unfilled portions. You can always modify the boot html file used to remove the template etc.
3. The USOCKET error is not an error, but a notification of an abrupt disconnect that was handled.

**Comment by mikelevins** [comment]
Thanks!
