### ISSUE TITLE
ESRAP fasl error

### ISSUE THREAD

**Issue by jonathanabennett** [rabbibotton/clog#194]
When running `(ql:quickload :clog)`, I receive the following error:

```
The values
  (#<FUNCTION (LAMBDA (ESRAP::PRODUCTION)
                :IN
                "/home/jonathanb/.cache/common-lisp/sbcl-2.2.5-linux-x64/home/jonathanb/quicklisp/dists/quicklisp/software/3bmd-20210411-git/parser.fasl") {53F4AA6B}>
   NIL NIL)

are not of type
  (VALUES FUNCTION &OPTIONAL)
   [Condition of type TYPE-ERROR]
```

**Comment by rabbibotton** [comment]
Did it work?

**Comment by jonathanabennett** [comment]
`(ql:update-all-dists)` did not fix it. I'm not sure how to clear quicklisp's cache? Where would I find that to delete it?

**Comment by jonathanabennett** [comment]
Deleting the cache also does not fix the problem.

**Comment by jonathanabennett** [comment]
I finally got it to work, here were the steps in the end:

1) Delete cache.
2) `(ql:update-client)`
3) `(ql:update-all-dists)`
4) quit REPL
5) In a new session, `(ql:quickload :clog/tools)`
