### ISSUE TITLE
It would be nice to crossbreed CLOG with Weblocks

### ISSUE THREAD

**Issue by svetlyak40wt** [rabbibotton/clog#2]
From the description of CLOG, it feels that it is close in spirit to [Weblocks](https://github.com/40ants/weblocks).

Probably it can be useful to create a CLOG powered widget for Weblocks to allow custom drawing and event handling.

**Comment by rabbibotton** [comment]
I'll take a look. In the mean time take a look at tutorial-11, there it shows how any html file can use CLOG. There is no reason that the boot.js can be added to dynamic output and then any thing with an ID (even svg content etc) can be manipulated live with CLOG.

**Comment by rabbibotton** [comment]
Can you give me a sample app in weblocks and maybe some comments on it how you would like to see them interact?

**Comment by svetlyak40wt** [comment]
I see this as a new type of widget for Weblocks where content of this widget is drawn using CLOG. This way a more dynamic content might be embedded into the sites using Weblocks.

By the way, recently I've renamed my Weblocks fork to Reblocks. Here you'll find a simple quickstart tutorial showing how to build an [application with a few widgets](https://40ants.com/reblocks/quickstart/#x-28REBLOCKS-2FDOC-2FQUICKSTART-3A-40QUICKSTART-2040ANTS-DOC-2FLOCATIVES-3ASECTION-29).

**Comment by rabbibotton** [comment]
With the builder you would do the following:
1. Make sure to load somewhere on you weblock/redbock page the js/boot.js file from CLOG (don't forget the CLOG server and any page containing CLOG objects must be on the same domain or you need iframes). You may need to adjust the ports manually in boot.js depending on how you configure your servers, as boot.js tries to connect via websockets to the same url and port as the webpage that contains it.
2. Create a <div> in Weblocks/Redblocks where you would like the CLOG content to show, assign that div an HTML ID.
3. In your CLOG app in your new window handler you just ATTACH to that ID. If you using CLOG Builder you just do your create-(panel name) to that attached object or use it like any other CLOG object to build your site in code.
