### ISSUE TITLE
Avoiding using the same lock for generating all script ids

### ISSUE THREAD

**Issue by shakatoday** [rabbibotton/clog#206]
Currently CLOG uses the same lock for generating all script ids. (if I understand it correctly)
It will affect the performance for multi-user applications.

How about one lock per connection id?
Or, maybe there's a better way.

**Comment by rabbibotton** [comment]
(proclaim '(type fixnum *new-id*)) (defglobal *new-id* 0)
(atomic-incf *new-id*)

That is ideal way on sbcl, there should be something similar for ecl

**Comment by rabbibotton** [comment]
https://shinmera.github.io/atomics/

**Comment by rabbibotton** [comment]
Implemented.

**Comment by shakatoday** [comment]
Thank you for your professional solution!
