### ISSUE TITLE
Avoiding id and post-data collision for "multipart/form-data;"

### ISSUE THREAD

**Issue by shakatoday** [rabbibotton/clog#207]
https://github.com/rabbibotton/clog/blob/91b229133dcc7e69cf1e8d2e0344067d47c3575f/source/clog-connection.lisp#L449-L455
When users access the application in the same second, ```get-universal-time``` generates the same ```id``` and ```post-data``` here. It means ```id``` and ```post-data``` collision.

I thought it was just about substituting ```get-universal-time``` with ```random-hex-string```, but ```post-data``` here uses the same value. Thus, my judgement is it could be not so trivial to solve the collision.

**Comment by rabbibotton** [comment]
I changed to using random-hex-string and adjust clog:form-multipart-data so would work.

**Comment by shakatoday** [comment]
Thank you for the patch.
Found a tiny related code to modify as well. 
#208
Thanks again.
