### ISSUE TITLE
still have same error compiling on windows 10, SBCL 2.2.7, after setting git to check out with cr/lf as directed

### ISSUE THREAD

**Issue by iantor** [rabbibotton/clog#212]
I reconfigured git for windows to check out with cr/lf, completely cleared quicklisp directory, reinstalled quicklisp, ultralisp.  Cloned the three clog git packages into local-projects (along with usocket, necessary because version in quicklisp has a reference to an obsolete var with sbcl 2.2.7)

executing (ql:quickload :clog)  still stops compilation with the same error (I believe):

[package clog-webgl]..........................
; file: c:/Users/ian/quicklisp/local-projects/clog/source/clog-document.lisp
; in: DEFMETHOD LOAD-SCRIPT (CLOG-DOCUMENT T)
;     (FORMAT NIL "$.getScript('~A', function() {~
;                               $(clog['document']).trigger('on-load-script',~
;                                                               '~A')})"
;             (CLOG:ESCAPE-STRING CLOG::SCRIPT-URL)
;             (CLOG:ESCAPE-STRING CLOG::SCRIPT-URL))
;
; caught ERROR:
;   during macroexpansion of
;   (FORMATTER "$.getScript('~A', function() {~
;                               $(clog['document']).trigger('on-load-script',~
;                                                               '~A')})").
;   Use *BREAK-ON-SIGNALS* to intercept.
;
;    error in FORMAT: Unknown directive (character: Return)
;     $.getScript('~A', function() {~
;                               $(clog['document']).trigger('on-load-script',~
;                                                               '~A')})
;                                    ^
.
debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1001DD8003}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "clog" "source" "clog-document">

**Comment by iantor** [comment]
relevant setting in .gitconfig is 
[core]
autocrlf = true

**Comment by rabbibotton** [comment]
Something still off. For now just get delete the line feeds and tildes from

 $(clog['document']).trigger('on-load-script',~
; 'A')})"

And let me know if compiles ok

N

**Comment by rabbibotton** [comment]
This is wrong setting. Needs to be : input not true

**Comment by iantor** [comment]
just realized that I had misread what you said.  I will reconfigure git as you originally directed (to check out as is), clear everything, and retry.

**Comment by iantor** [comment]
found the problem.  There were two gitconfig files, one was overriding the other.  Once I removed the erroneous one, and cleared quicklisp and re-cloned the repo items, compilation completed successfully.  Command that helped me figure this out was git config --list --show-origin

**Comment by rabbibotton** [comment]
Fantastic :) I look forward to see the great things you will do with CLOG!

**Comment by iantor** [comment]
Excited to finally get started.
