### ISSUE TITLE
(clog:open-manual) doesn't work for me on Win 10, sbcl 2.2.7, Chrome

### ISSUE THREAD

**Issue by iantor** [rabbibotton/clog#223]
Latest clog.
Instead of opening the browser with the manual, the explorer window opens.

CL-USER> (clog:open-manual)
Unable to open browser.

Subprocess with command "explorer \"c:/Users/ian/quicklisp/local-projects/clog/./doc/clog-manual.html\""
 exited with error code 1
NIL

I have no problem opening the manual page directly from the github page.

**Comment by rabbibotton** [comment]
I will see if can fix but not sure will be able to. You can also start clog-builder and choose the manual from the menu.

**Comment by iantor** [comment]
I was just reporting it for completeness.  Windows shell interfacing can be a bear, as I have noticed in elisp.  Once I'm up to speed with Common Lisp and Git, will see if I can fix it.

**Comment by rabbibotton** [comment]
Going to close this ticket as alternate solutions exist like the github version.
