### ISSUE TITLE
Loading :clog/tools produces a compile file error

### ISSUE THREAD

**Issue by kaeland** [rabbibotton/clog#227]
Hi @rabbibotton, 

I use a 2017 macbook to run clog. I've recently pulled the latest git changes into my local clog repository, and I am attempting to load **:clog/tools**. However, whenever I use **(ql:quickload :clog/tools)**, I see a compile file error. I've taken a screenshot of what I'm seeing. I'm wondering if this has happened to you or anyone else as well? 

Do you have any advice on how to resolve the error?

![Screen Shot 2022-09-03 at 6 37 42 PM](https://user-images.githubusercontent.com/17867788/188289696-845b592b-9001-40d6-8f94-924db9fe2245.png)

**Comment by rabbibotton** [comment]
Do you have the latest clog-ace and clog-terminal also pulled from GitHub
or UltraLisp?

**Comment by kaeland** [comment]
No, I will pull them and see if this help. Thank you.

**Comment by kaeland** [comment]
@rabbibotton Thank you! That worked! I needed to fork and pull those projects locally. Then I needed to run `(ql:update-all-dists)` in the sly repl. Once this was done, I could then run `(ql:quickload :clog/tools)` successfully.

**Comment by rabbibotton** [comment]
Great!
