### ISSUE TITLE
clog-multimedia; media-duration causes parse error

### ISSUE THREAD

**Issue by faeredia** [rabbibotton/clog#23]
(media-duration ((obj clog-multimedia)) is throwing an error; 
it is fetching the property "loop" instead of "duration", then failing to parse as an integer

definition should change to:
```
(defmethod media-duration ((obj clog-multimedia))
  (property obj "duration"))
```
This returns a string-of-float, parse-integer will continue throwing parse error
consider using parse-float or just returning the string

Note that
(media-position ...)
is currently returning a string (these should be consistent)

**Comment by faeredia** [comment]
(property obj "duration") can also return "NaN". If we choose to have media-duration and media-position return floats, this will need to be handled. otherwise the user will have to handle the NaN case themselves

**Comment by rabbibotton** [comment]
I'll add parse-float and see about making the changes now.

**Comment by rabbibotton** [comment]
I made the changes and will also take  a look through other code. Thanks
