### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [rabbibotton/clog#235]
Building with SBCL 2.2.7.28-02bc916fd / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id fa23c4d881c0e83b9f0784ae85d4629ac2e879b4

*clog/tools* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Package QUICKLISP-CLIENT does not exist. Line: 143, Column: -1, File-Position: 10118 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/clog/c82573d0917c14205abb276c78fe0878235824d8/clog-20220925-git/tools/systems.lisp" {102CB80363}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10016D0003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "clog/tools" "systems">

```

[Full log here](http://report.quicklisp.org/2022-09-25/failure-report/clog.html)

**Comment by quicklisp** [comment]
For context, quicklisp is not part of the quicklisp dist build process. Projects should not use quicklisp client functions in general.

**Comment by rabbibotton** [comment]
As the CLOG IDE uses quicklisp as fairly integral part of the project system is there a reason for this policy? Is there a way to change it if there is not a reason?

**Comment by rabbibotton** [comment]
If I need to remove how much time is there to next release, my holidays start for next few days soon?

**Comment by quicklisp** [comment]
The original reason was to discourage embedding of "(ql:quickload ...)" in
sources, and to encourage the creation of proper dependencies in system
definitions. And it's also to discourage the assumption that quicklisp is
everywhere, which makes libraries less portable, as not everyone uses or
wants to use Quicklisp.

I recognize it's a different situation when the library or application is
explicitly related to working with Quicklisp and quicklisp systems. In that
case, it's a technical limitation on my side that Quicklisp isn't loaded
and can't be referenced during the dist build process.

Other projects have worked around this by deferring Quicklisp symbol
lookup, via something like (funcall (read-from-string "ql:quickload") ...)
or similar.

I don't have a short-term fix for including Quicklisp in the dist build
environment, but it's on my todo list.

**Comment by rabbibotton** [comment]
Provided I have power (hurricane already making issues) I'll get a fix in
tomorrow God willing

**Comment by rabbibotton** [comment]
done, thanks!
