### ISSUE TITLE
Demos broken?

### ISSUE THREAD

**Issue by simendsjo** [rabbibotton/clog#243]
Has `SET-STYLE` been removed in favor of `SET-STYLES` or similar without updating demos?

```
The function CLOG::SET-STYLE is undefined.
   [Condition of type UNDEFINED-FUNCTION]

Restarts:
 0: [CONTINUE] Retry calling CLOG::SET-STYLE.
 1: [USE-VALUE] Call specified function.
 2: [RETURN-VALUE] Return specified values.
 3: [RETURN-NOTHING] Return zero values.
 4: [ABORT] abort thread (#<THREAD "CLOG connection e908c8024e3c54a35750f857580c713b" RUNNING {1007CB4D33}>)

Backtrace:
 0: ("undefined function" #<CLOG:CLOG-DIV {1007DE1AD3}> "text-align" :CENTER)
 1: (CLOG-DEMO-1::DISPLAY-SPLASH #<CLOG:CLOG-BODY {1007CBFF23}>)
```

**Comment by rabbibotton** [comment]
Where are you seeing set-style? That function existed a loooong time ago to support use of defsetf with style which ended up creating issues with inheritance so all set-* for properties were removed in favor of directly defining setf functions/methods (set-styles is an exception as it is about setting multiple properties at once).

**Comment by rabbibotton** [comment]
Make sure to use the UltraLisp versions (or get from github clog, clog-terminal and clog-ace)

**Comment by simendsjo** [comment]
Hmm, did a dist update, reload, and the error disappeared. Not sure what went wrong here.
