### ISSUE TITLE
Can't replace CLOG::SET-CONNECTION-DATA-ITEM with NIL because it is undefined

### ISSUE THREAD

**Issue by kaeland** [rabbibotton/clog#244]
@rabbibotton Hi Dr. Botton, I'm currently seeing an error when running the `(clog-tools:clog-builder)` command in the repl. When I run this function I am seeing this: 

<img width="1440" alt="Screen Shot 2022-11-04 at 9 47 44 PM" src="https://user-images.githubusercontent.com/17867788/200151265-62a60106-249e-4908-9331-3f3ce8a60a7e.png">

Having used slime's `v` command to locate the line where the exception occurs, I am navigated to line `58` of the `clog-system.lisp` file: 
<img width="1440" alt="Screen Shot 2022-11-04 at 9 48 18 PM" src="https://user-images.githubusercontent.com/17867788/200151317-9ff6f281-12ea-4090-89fe-7dde0daaa89a.png">

I may have located [the source of the exception here](https://github.com/rabbibotton/clog/commit/02e4ed8fc18596f086fe9aac01fea02d8aa77edb#diff-87236dc620008e038da5f473635c0c744e446f19c1209cf4e8d8c89847af45a1R510-R511), but I'm not sure of how to resolve this. Do you have any advice? 

**Please note**, the clog builder does not boot/start on `localhost:8080/builder` for me. I'm only seeing a blank/white screen. Changing the port has not worked either.

**Comment by rabbibotton** [comment]
Just to confirm, you are using the lates CLOG from UltraLisp or GIT (and if using GIT also the latest CLOG-Ace and CLOG-Terminal)?

Was it previously running?

Can you run (clog:run-demo 1) does that function as expected?

**Comment by rabbibotton** [comment]
QuickLisp is now up to date as well. Let me know when can if this solves things.

**Comment by kaeland** [comment]
@rabbibotton I apologize for the late reply. I've just opened the builder a few minutes ago, and it appears to be working fine. Thank you!
