### ISSUE TITLE
Connection errors: browser can't communicate with server.

### ISSUE THREAD

**Issue by MonadMania** [rabbibotton/clog#246]
I'm on Windows 10 using SBCL, and I've tried this on two separate machines.  My browsers are Firefox and Chrome.  

Page changes and form submissions trigger the following error:

`[2022-11-19 20:27:16 [ERROR]] Error while processing connection: The condition Couldn't write to #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8080, peer: 127.0.0.1:51426" {1007C6AC73}>:
                                                                                 The specified network name is no longer available. occurred with errno: 0.`

This makes communication between the browser and LISP impossible.  Print and format statements don't work at all in event handlers.  Most tutorial examples work, but the mutlipart data upload example doesn't work - nothing prints to the REPL.

This specific error came from tutorial 17, but it's the same error every time.  https://github.com/rabbibotton/clog/blob/main/tutorial/17-tutorial.lisp

Can someone please help me find the cause of this error?  I'd like to make the tutorials work.

**Comment by rabbibotton** [comment]
Does it occur with even tutorial 1?

Can you run the builder (ql:quickload :clog/tools) (clog-tools:clog-builder)

That error is actually btw being generated by the http layer which means is a network error. So, check you windows 10 firewall.

**Comment by MonadMania** [comment]
@rabbibotton thank you for checking in. Yes, it even happens in Tutorial 1. I can run the builder, but I don't know how to use it yet. Browser-side changes occur, but communication with the REPL doesn't work.

Do you know what changes to make to the Windows firewall? I've tried enabling inbound connections to SBCL, but this hasn't worked.

**Comment by MonadMania** [comment]
By the way, the CLOG builder can create new projects and similar things. I made a test project which showed up in my local file system.

**Comment by rabbibotton** [comment]
That is even more strange, as the builder is a clog app itself.  Are you running a 32bit windows or 64bits? I know that sbcl historically has some issues on win32.

**Comment by MonadMania** [comment]
I'm running 64-bit Windows on both machines, and my Emacs and SBCL are both 64-bit.

**Comment by MonadMania** [comment]
In tutorial 1, I added a print statement to the on-click handler. On my machines, nothing prints to the REPL which launched the page. Similarly, in tutorial 17, a text file uploaded to the app should be printed in the REPL, but it's not.

`(defun on-new-window (body)
  "On-new-window handler."
  (let ((hello-element
          (create-child body "<h1>Hello World! (click me!)</h1>")))
    (set-on-click hello-element
                  (lambda (obj)
                    (declare (ignorable obj))
                    (setf (color hello-element) :green)
                    (print "Operation succeeded."))))) ; Will this print to the REPL?`

**Comment by rabbibotton** [comment]
Can you send me a screenshot of your repl startup?

You are seeing the Hello World on the browser though correct?

**Comment by MonadMania** [comment]
The REPL gives an error, but the page loads successfully.
![image](https://user-images.githubusercontent.com/1771723/203137758-7b9789c6-e0cd-43cc-82a7-30f4738a8c62.png)
The URL and icon load correctly.
![image](https://user-images.githubusercontent.com/1771723/203137934-ae6c9cc0-50f6-444c-aef7-edfd227e2e4d.png)
"Hello World!" Shows up.
![image](https://user-images.githubusercontent.com/1771723/203138014-3b366245-db74-46dd-9df5-79b34a31c8dc.png)

The on-click handler executes. 
![image](https://user-images.githubusercontent.com/1771723/203138145-79662858-b61f-4eeb-946b-2ed5032a02dd.png)

However, the print statement disappears into the ether. Changing to a format statement, in various iterations, didn't seem to help.
![image](https://user-images.githubusercontent.com/1771723/203138198-477c3e37-204c-4814-ba85-601e3a0192e9.png)

**Comment by MonadMania** [comment]
I looked into error code 1, and from what I see, it's a "wrong function call" (not that I know what that means in this case).

**Comment by MonadMania** [comment]
Here's what happens when I close the browser: the new error message shows up above the current REPL prompt and below the NIL that open-browser returned.
![image](https://user-images.githubusercontent.com/1771723/203139056-9abd53d7-e944-4fb9-ae5e-1f393ead6b84.png)

**Comment by MonadMania** [comment]
The following successfully printed to the REPL from the on-click handler.
`(format #.standard-output "Hello from thread!")`

I'm using SLIME version 2.24, which came bundled with Portacle. It turns out that I _was_ receiving the print statements, but they were being channeled into the *inferior-lisp* buffer instead of the REPL - silly me.

I appreciate your time and effort. Thank you. By the way, using this information, I was able to upload the file in Tutorial 17.

**Comment by rabbibotton** [comment]
Consider upgrading - https://github.com/rabbibotton/clog/blob/main/WINDOWS.md

**Comment by rabbibotton** [comment]
BTW one reason to upgrade is that the print statements etc will work with newer slimes etc
