### ISSUE TITLE
`clog:run` sometimes runs forever if page is refreshed

### ISSUE THREAD

**Issue by bpseudopod** [rabbibotton/clog#271]
# Expected behaviour
When a browser page with an active clog connection is refreshed, the `run` function should return, allowing per-window cleanup code to be called.

# Actual behaviour
Sometimes, although not always, the run function will never return, despite there no longer being a page to communicate with.

# To reproduce
Evaluate
```lisp
(ql:quickload :clog)
(clog:run-demo 2)
```
In the CLOG page in the browser, enter chat handle and join the room, refresh, repeat several times with different names. Now inspect the user list:
```lisp
(in-package :clog-demo-2)
(hash-table-count *global-list-box-hash*) ;;#=> some number that isn't 1
;; If we check the divs, they're all validp...
(mapcar #'validp (alexandria:hash-table-values *global-list-box-hash*)) ;;#=> (t t t ...)
;; but clog:connection-data returns nil on all the garbage connections
(mapcar #'connection-data (alexandria:hash-table-values *global-list-box-hash*)) ;;#=> (#<HASH-TABLE> nil nil ...)
```

**Comment by rabbibotton** [comment]
I am not seeing this behavior. What browser(s) are you using?
Also there maybe a second or two before return of run. Also some browsers in anticipation of another connection may keep things alive longer. Try your experiment closing down the browser completely a few times and let me know if still the case.

**Comment by tinkerttoy** [comment]
I tested it on Firefox 110, Chrome 110, and Midori 9.0 (a webkit-based browser, for the sake of completeness). The issue only appears on Firefox.
When I test with Firefox, triggering the bug, the logs look like this:
```
New connection id - 7c29822f9d1c9d8c22c9c14869cdeb44 - #<SERVER {1005460B43}>
Reconnection id - 7c29822f9d1c9d8c22c9c14869cdeb44 to #<SERVER {10054D09C3}>
New connection id - 3613a1120e842529da6b6914c0246f6d - #<SERVER {10054F09E3}>
[2023-02-20 13:58:10 [ERROR]] Error while processing connection: Condition USOCKET:CONNECTION-ABORTED-ERROR was signalled.
Reconnection id - 3613a1120e842529da6b6914c0246f6d to #<SERVER {10055909D3}>
[2023-02-20 13:58:12 [ERROR]] Error while processing connection: Condition USOCKET:CONNECTION-ABORTED-ERROR was signalled.
New connection id - 120b8f77b954ba2632d2eb65c5ad9dc9 - #<SERVER {10055B89E3}>
```
but when I test with Chromium, which doesn't trigger the bug, the logs look like this:
```
New connection id - 447b00adbefab78b815193dd5a22279b - #<SERVER {1005848733}>
[2023-02-20 13:59:54 [ERROR]] Error while processing connection: Condition USOCKET:CONNECTION-ABORTED-ERROR was signalled.
New connection id - 03fd6f42c8a731174063cce68f30717d - #<SERVER {10058D0733}>
[2023-02-20 13:59:57 [ERROR]] Error while processing connection: Condition USOCKET:CONNECTION-ABORTED-ERROR was signalled.
New connection id - 0e569fbe9b9c4ebff570ddc7a21471eb - #<SERVER {1005950733}>
```

These bugged connections are long-lived; I left the CLOG server running overnight and the problematic handler threads were still there in the morning. Completely closing the browser, as you suggested, doesn't cause them to go away either.

**Comment by rabbibotton** [comment]
I still can not reproduce with firefox on Mac. However despite it showing on one browser, it is more likely an issue with usocket or worse at the OS level. What OS are you using?
