### ISSUE TITLE
Tutorial does not work after (ql:update-all-dists)

### ISSUE THREAD

**Issue by ebrasca** [rabbibotton/clog#275]
After updating the libraries and running (clog:run-tutorial 1) , I get:

> Not Found
The requested URL / was not found on this server.
[Hunchentoot 1.3.0](http://weitz.de/hunchentoot/) [(SBCL 2.3.2)](http://www.sbcl.org/) at 127.0.0.1:8080

I was unable to find the root of the problem.

**Comment by aykaramba** [comment]
You should see something like this after run the command:

CL-USER> (clog:run-tutorial 1)


 ---- The tutorial src is located at: /home/***/mnt/work/common-lisp/clog/./tutorial/01-tutorial.lisp
Hunchentoot server is started.
Listening on 0.0.0.0:8080.
HTTP listening on    : 0.0.0.0:8080
HTML root            : /home/***/mnt/work/common-lisp/clog/static-files/
Long poll first      : no
Boot function added  : no
Boot html source use : compiled version, when no file
Boot js source use   : compiled version
Boot file for path / : /boot.html
New connection id - bf21e458a232cd4783628486f94dc849 - #<SERVER {1005479F33}>
NIL
NIL
0 (0 bits, #x0, #o0, #b0)

You don't get this?

**Comment by aykaramba** [comment]
No idea where the smiley face comes from.  Weird.

**Comment by aykaramba** [comment]
Oh, you installed it from quicklisp respos?  Actually, just git clone it from github: https://github.com/rabbibotton/clog

Uninstall the one from the ql repos and put the code in your local-projects folder and it should work.

**Comment by ebrasca** [comment]
I tried cloning it with git but I still get the same problem.

 ---- The tutorial src is located at: /home/ebrasca/common-lisp/web/clog/./tutorial/01-tutorial.lisp
Hunchentoot server is started.
Listening on 0.0.0.0:8080.
HTTP listening on    : 0.0.0.0:8080
HTML root            : /home/ebrasca/common-lisp/web/clog/static-files/
Long poll first      : no
Boot function added  : no
Boot html source use : compiled version, when no file
Boot js source use   : compiled version
Boot file for path / : /boot.html
NIL
NIL
0

**Comment by rabbibotton** [comment]
(clog:shutdown)
(clog:run-tutorial 1)

also what OS are you using? Any firewalls in place?

**Comment by aykaramba** [comment]
Yup, looks like it's running correctly.

Open up your browser and go to http://localhost:8080

**Comment by ebrasca** [comment]
I am using Gentoo GNU/Linux
Linux 6.2.8
Hunchentoot 1.3.0
SBCL 2.3.2
ASDF 3.3.5

I don't have nothing that will block local access.
Is it relevant to mention I added ultralisp?

**Comment by aykaramba** [comment]
Not really no.  Your message literally says that you have the server running locally:  HTTP listening on : 0.0.0.0:8080

You get nothing in your browser @ localhost:8080 ?

Blank page?

**Comment by aykaramba** [comment]
Aha!  Interesting.  I had to stop using ultralisp a while back as I did not fully understand how it interacts with ql either.  Apologies, I don't know the answer to that.

**Comment by cneira** [comment]
> After updating the libraries and running (clog:run-tutorial 1) , I get:
> 
> > Not Found
> > The requested URL / was not found on this server.
> > [Hunchentoot 1.3.0](http://weitz.de/hunchentoot/) [(SBCL 2.3.2)](http://www.sbcl.org/) at 127.0.0.1:8080
> 
> I was unable to find the root of the problem.

Same here, I was using clog a couple of months ago for some projects, did (ql:update-all-dists ) and now does not work, not even the tutorials.

**Comment by cneira** [comment]
This issue should be closed, there was an old version of clog in my quicklisp path, 
after removing it and installed again with 

`lisp
(ql:update-all-dists)
`

tutorials started working again.

**Comment by rabbibotton** [comment]
great!
