### ISSUE TITLE
Multiple connections?

### ISSUE THREAD

**Issue by mmontone** [rabbibotton/clog#277]
When I have a tab with a CLOG application opened, and then I open a separate browser tab pointing to that same application, the first tab stops responding (now the new browser tab is in charge).

Is it possible to have multiple browser connections to the same app? 

Thanks

**Comment by rabbibotton** [comment]
Not sure I understand, you can have (and I regularly do) have 100s of connections, different browsers machines etc at same time. Try running the chat demo - demo 2 as in that example you have multiple connections and sharing between each data.

David Botton

**Comment by mmontone** [comment]
Yes, I'm doing it wrong because I'm using global variables for assigning different parts of my application, but that won't scale to several connections, obviously.
I wonder if the concept of "connection-variable" could make sense, where I can get the value of a variable bound to the current connection.

Ok. I'm just thinking out loud. I'll have a look at chat demo and probably web demos too.

**Comment by mmontone** [comment]
Thanks
