### ISSUE TITLE
custom slot fail

### ISSUE THREAD

**Issue by gassechen** [rabbibotton/clog#279]
Hello. I'm following the Clog plunger videos. I have a problem with "Custom Slots". when i insert them it is reflected in this way in the code and gives an error 
` (selectablep :accessorselectablep :initform nil)`

 On the other hand to the Reload the builder, or the application, that field appears empty

**Comment by rabbibotton** [comment]
It should be - (selectablep :accessor selectablep :initform nil)
space missing after accessor

it is currently not handling errors well. Let me know if that does it

**Comment by gassechen** [comment]
Is my firefox version, in chrome no error

**Comment by rabbibotton** [comment]
I can not reproduce this, closing. Is still happening for you let me know.
