### ISSUE TITLE
CLOG apps don't survive sleep / hybernation

### ISSUE THREAD

**Issue by Mr-Dispatch** [rabbibotton/clog#281]
[client & server on the same machine]
Is this even solvable ? Temporary session retention (using monotonic timers) ?
[Of course, that would massively degrade security in cases where the client & server are on separate machines ... DOS / Session stealing ... ]

**Comment by rabbibotton** [comment]
On local machines there are no issues with sleep and suspend. I assume you are talking about between networked machines. If the interruption is long enough than it is viewed as a disconnect and so would not work. 

If you wanted your app to survive a disconnect and a new connection that would be something to design in to your app.  Disconnects of days months etc

Summary on local machine I’ve never seen an issue, for remote connections you will have to design in persistence.

**Comment by Mr-Dispatch** [comment]
"On local machines there are no issues with sleep and suspend."
I call bullshit on this. EVERY time I put mu notebook to sleep / hybernation, CLOG builder dies. What can I submit as evidence ?

**Comment by Mr-Dispatch** [comment]
The cow dung might be the state of my Windows install - upgraded for some 2-3 years, enjoyed several versions of Visual Studio and whatnot ... Just that it really happens.

**Comment by jpe90** [comment]
I couldn't reproduce this. I tested CLOG apps and CLOG builder on x86-64 Windows, ARM Mac, and X86-64 Linux, all installed from Ultralisp. I ran local apps and CLOG builder on each system, hibernated, resumed the system, and checked app functionality/database connectivity. Didn't have any issues.

I'm not sure how this issue can move forward considering there are no REPL logs, browser logs, system logs or anything indicating what the problem might be. 

@Mr-Dispatch Please don't be abusive or disrespectful to free software maintainers.
