### ISSUE TITLE
Change links away from Reddit (or add direct links to the Google Docs)

### ISSUE THREAD

**Issue by jonathanabennett** [rabbibotton/clog#283]
When I want to see worked examples for clog-builder, the link goes to the Reddit post, where I then have to click again to get the Google doc. The reddit post is good to have because it includes the comments and discussion, but it would be more convenient if the direct link was there as well. Something like this, perhaps:

1. [Chat App](https://docs.google.com/document/d/149DUQqdmV8OL8C22l_WHRxxgWbkrEIzcmwkvqltOU2w/edit):  [Reddit post with conversation](https://www.reddit.com/r/lisp/comments/sj1tv5/clog_builder_tutorial_1_a_chat_app_from_start_to/)

**Comment by jonathanabennett** [comment]
I'm happy to submit a pull request for this, I just wanted to see if you liked that format (have the name of the tutorial be the direct link and then the reddit post after it).

**Comment by rabbibotton** [comment]
Great idea!!

**Comment by rabbibotton** [comment]
Are you still planning on this jonathanabennett

**Comment by jonathanabennett** [comment]
Sorry, I got buried in summer planning. I should be able to do this as soon as my family heads back home.
