### ISSUE TITLE
iPhone build

### ISSUE THREAD

**Issue by josharmenta** [rabbibotton/clog#291]
Is there a "how-to" or other documentation on building a clog app for iOS? 

I know there was a fork of Clog but is that specific fork still necessary?

**Comment by rabbibotton** [comment]
Sorry for delays. It has been my intent to work on builds directly with out the fork but have not done so yet.

**Comment by rabbibotton** [comment]
I have closed and caught up with various issues, I plan on working on installs soon. My first version will actually be something a bit more exciting. I plan on using WASM version of ECL. This will allow you to deliver using https://cordova.apache.org/ on every platform in one shot and test on your own machine etc. You of course can use any other existing framework that would deliver an HTML app once I have this running.

**Comment by rabbibotton** [comment]
Have you tried setting up a simple iOS/android project and using ECL or SBCL as a dynamic lib with clog btw? Or EQL and a qt browser?

**Comment by josharmenta** [comment]
So sorry I didn't get back to you on this btw. I actually have been able to get the EQL/QT Bindings to work with a simple app. I'll keep playing around with it.
