### ISSUE TITLE
Form-dialog (clog-gui) has issues with values having single quotes

### ISSUE THREAD

**Issue by sabracrolleton** [rabbibotton/clog#295]
Example. Use tutorial 22 and in the on-dlg-form, insert a single quote in the string "Real Name". 

E.g. "Real N'ame". 

The single quote and any text after the single quote will not show in the form input. In this example, the text showing will be "Real N".

I have not been able to figure why.

**Comment by rabbibotton** [comment]
I am not seeing this, are you using github version or the quickload version. If quickload version try (ql:update-all-dists) as may have an older version of clog.

**Comment by sabracrolleton** [comment]
Sigh. I am not seeing it now either.
