### ISSUE TITLE
[Windows] open-window displays a failure even though window opens.

### ISSUE THREAD

**Issue by tmheath** [rabbibotton/clog#296]
Unable to open browser.

Subprocess with command "explorer \"http://127.0.0.1:8080\""
 exited with error code 1

The browser window does open properly, further I was using this a while ago and it seemed to work just fine.
Platform is MS Windows 10 Pro 64 bit, SBCL.

**Comment by rabbibotton** [comment]
It is an issue with trivial-open-browser and not likely to be fixes sadly and reacts differently on different versions of windows.

Since this is not a production component and harmless, I don't plan on fixing.
