### ISSUE TITLE
set-on-click is repeating data

### ISSUE THREAD

**Issue by K1D77A** [rabbibotton/clog#305]
Hi I seem to have run into a problem
I have my GUI made with clog-gui 
![image](https://github.com/rabbibotton/clog/assets/10334164/b4f1d113-5733-4ab3-9aff-a87fcedaabf5)

I then have the Rules dropdown which has one option and when selected I have:
![image](https://github.com/rabbibotton/clog/assets/10334164/7ad0a770-1dde-4075-8eb2-14c56de0d1fd)

Now what is strange is that whenever i click on any of the options I get the same data displayed in the new window. 
![image](https://github.com/rabbibotton/clog/assets/10334164/3b7841a3-e695-49c2-bbbf-c215a90bb101)

No matter which I click on I only get the data for the PREMIUM category. 

The code I have is the following:

```lisp
(defun inspect-rules (o category rules)
  (let ((gui (create-gui-window o
                                :title (format nil "Substack ~S Rules" category)
                                :width 700)))
    (dolist (rule rules)
      (let ((d (create-div (window-content gui)
                           :class "rules"
                           :content
                           (spinneret:with-html-string
                             (:div :class "rule"
                                   (:h3 (format nil "Name: ~A"
                                                (breca::name rule)))
                                   (:h4 (format nil "Weight: ~D"
                                                (breca::weight rule)))
                                   (:pre
                                    (format nil "~S" (breca::fun-as-list rule))))))))))))
         
(defun substack-rules (body)
  (let ((r (gethash (find-class 'breca::substack) breca::*resource-rules*))
        (gui (create-gui-window body :title "Rule Categories")))
    (loop :for (category rules) :on r :by #'cddr 
          :do (let ((d (create-div (window-content gui) :class "rules"
                                                        :content
                                                        (spinneret:with-html-string
                                                          (:div :class "rule"
                                                                (:p category))))))
                (set-on-click d (lambda (o)
                                  (inspect-rules o category rules)))))))
   
```

And in my main I just have 
```lisp
         (rules (create-gui-menu-drop-down menu :content "Rules"))         
         (substack-rule (create-gui-menu-item rules :content "Substack"
                                                    :on-click 'substack-rules))
```
I have gone through and checked that all of the values in the set-on-click closure are correct... 

Any help would be greatly appreciated. 
Thanks.

**Comment by sabracrolleton** [comment]
You need to do a little extra work to deal with the clog closures. Does this do what you want?

    (defun substack-rules (body)
      (let ((r (gethash (find-class 'breca::substack) breca::*resource-rules*))
            (gui (create-gui-window body :title "Rule Categories")))
        (loop :for (category rules) :on r :by #'cddr 
              :do (let ((my-category category) ; for clog closure purposes
                        (my-rules rules) ; for clog closure purposes
                        (d (create-div (window-content gui) :class "rules"
                                       :content
                                       (spinneret:with-html-string
                                        (:div :class "rule"
                                              (:p my-category))))))
                    (set-on-click d (lambda (o)
                                      (inspect-rules o my-category my-rules)))))))

**Comment by K1D77A** [comment]
Yes it did fix it. Thanks.
What a silly problem :joy:
