### ISSUE TITLE
Clog-Builder cannot open projects it creates.

### ISSUE THREAD

**Issue by aykaramba** [rabbibotton/clog#307]
I was doing some testing with clog-build and I have noticed the following behaviour:

1) Any project not created using clog-builder can be explored using the PROJECT WINDOW.

2) Any project created using the PROJECT WINDOW (new) or BUILDER / NEW APPLICATION TEMPLATE cannot be explored using the PROJECT WINDOW.  I can select any of the projects creating using BUILDER  but the PROJECT WINDOW cannot explore the runtime system, nor runtime dependencies nor VIEW DIR. 

Before posting various errors that pop up here or there, are there any other users experiencing the same?

I have been hand coding everything for the time being so I don't know when these issues may have appeared and I am curious if it is just my install or if others see the same behaviour.  I have the latest version of Clog.

**Comment by rabbibotton** [comment]
I have not seen this on any of the platforms or installations I am using.

**Comment by aykaramba** [comment]
I have to get back to this to do more testing, ignore for now, will provide updates as necessary.  thanks.

**Comment by rabbibotton** [comment]
Ok so just open another ticket if still see.
