### ISSUE TITLE
Destroy is not applied to child elements

### ISSUE THREAD

**Issue by sabracrolleton** [rabbibotton/clog#311]
My specific example: create a clog-select box with a label, then call destroy on the select box. The select box itself is destroyed but the label is left as an artifact on the browser with no obvious (to me) way to get rid of it.

I am not using builder and I use destroy in progressive dialog boxes.

**Comment by rabbibotton** [comment]
Can you give me an example? Most likely the label is not a child on the DOM to the select box. You can put both in div and delete the div and then both should be destroyed with destroy.
