### ISSUE TITLE
Is there a reason form-dialog does not allow textareas?

### ISSUE THREAD

**Issue by sabracrolleton** [rabbibotton/clog#312]
Form-dialog is convenient, except when the user is inputing text that requires a textarea. Is there a particular reason that I am missing for the limitation? Otherwise I can submit a pull request.

**Comment by rabbibotton** [comment]
No particular reason off hand. If you have a solution that works sure
submit pull.

**Comment by sabracrolleton** [comment]
Ok. Submitted pull request.

**Comment by rabbibotton** [comment]
merged
