### ISSUE TITLE
Cannot run 33-tutorial.lisp

### ISSUE THREAD

**Issue by aykaramba** [rabbibotton/clog#325]
I downloaded a new copy of CLOG and tried to run 33-tutorial.lisp.  I get the following error:

The function
  #<STANDARD-GENERIC-FUNCTION CLOG:OBJ (1)>
requires at least 2 arguments.
   [Condition of type SB-INT:SIMPLE-PROGRAM-ERROR]

Restarts:
 0: [ABORT] abort thread (#<THREAD "CLOG connection f64a572275534028011d04eb1e5b1662" RUNNING {1004109C63}>)

Backtrace:
 0: (SB-INT:%PROGRAM-ERROR "~@<The function ~2I~_~S ~I~_requires at least ~W argument~:P.~:>" #<STANDARD-GENERIC-FUNCTION CLOG:OBJ (1)> 2)
      Locals:
        #:G2 = "~@<The function ~2I~_~S ~I~_requires at least ~W argument~:P.~:>"
        SB-DEBUG::MORE = (#<STANDARD-GENERIC-FUNCTION CLOG:OBJ (1)> 2)
 1: (SB-PCL::ERROR-NEED-AT-LEAST-N-ARGS #<STANDARD-GENERIC-FUNCTION CLOG:OBJ (1)> 2)
      Locals:
        FUNCTION = #<STANDARD-GENERIC-FUNCTION CLOG:OBJ (1)>
        N = 2
 2: (SB-PCL::INITIAL-DFUN #<STANDARD-GENERIC-FUNCTION CLOG:OBJ (1)> NIL)
      Locals:
        ARGS = NIL
        GF = #<STANDARD-GENERIC-FUNCTION CLOG:OBJ (1)>
 3: (CLOG-TUT-33::ON-NEW-WINDOW #<CLOG:CLOG-BODY {10048844A3}>)
      Locals:
        BODY = #<CLOG:CLOG-BODY {10048844A3}>
 4: ((LABELS BORDEAUX-THREADS::%BINDING-DEFAULT-SPECIALS-WRAPPER :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
      [No Locals]
 5: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
      [No Locals]
      Catch-tags:
        SB-THREAD::%RETURN-FROM-THREAD
 6: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
      [No Locals]
 7: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
      [No Locals]
      Catch-tags:
        SB-THREAD::%ABORT-THREAD
        SB-IMPL::%END-OF-THE-WORLD
        SB-INT:TOPLEVEL-CATCHER
 8: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
      [No Locals]
 9: (SB-THREAD::RUN)
      [No Locals]
10: ("foreign function: call_into_lisp_")
      [No Locals]
11: ("foreign function: funcall1")
      [No Locals]

I am getting better with Lisp but don't know how to fix that issue yet.  Any suggestions on a fix?

Thanks.

**Comment by rabbibotton** [comment]
What is the version of your sbcl compiler?
You downloaded how? (git pull / QuickLisp / UltraLisp / release download)

I can confirm that Tutorial 33 runs ok Linux, Win and Android and no recent changes should affect it.

**Comment by rabbibotton** [comment]
Were you able to get this working?

**Comment by aykaramba** [comment]
I have an emergency to address first, my apologies.   I will follow up this evening.  My apologies for not getting back to you on this faster.

**Comment by aykaramba** [comment]
Rabbi, you are correct, there is no problem with tutorial 33.  I moved clog around on my system and it turned out I had a backup of clog files in some weird subfolder that quicklisp found.  I did not know that ql did a recursive search to find systems in ~/common-lisp or ~/quicklisp/local-projects.

Apologies for the noise, this is closed.
