### ISSUE TITLE
No "name" attribute in "input" element - create-form-element remove :name key

### ISSUE THREAD

**Issue by fferrere** [rabbibotton/clog#336]
Hey,

First, i apologize about my english.

Form action with get method do not work in tutorial 17.

The `create-form-element` method in `clog-form.lisp` removes :name keys, so no "name" attribute is created for input element.
```
(dolist (key '(:name :html-id :auto-place))
    (remf args key))
```
Without "name" attribute, the input element is never sent.

Removing `:name` from the dolist function get the thing right.
```
(dolist (key '(:html-id :auto-place))
    (remf args key))
```

**Comment by rabbibotton** [comment]
Thank you for finding that regression. Fixed
