### ISSUE TITLE
loading loading clog/tools fails with ECL 23.9.9 on Android/Termux

### ISSUE THREAD

**Issue by argentcorvid** [rabbibotton/clog#341]
I get the following output when loading from ultralisp:

To load "clog/tools":
  Load 1 ASDF system:
    clog/tools
; Loading "clog/tools"
;;; Internal error:
;;;   ** There is no package with the name ASDF/SYSTEM-REGISTRY

Then debugger pops up saying:

Condition of type: COMPILE-FILE-ERROR
COMPILE-FILE-ERROR while compiling #<cl-source-file "clog/tools" "panel-projects">

Output of system-apropos:
#<system clog/tools / rabbibotton-clog-20240418035234 / ultralisp 20240418090500>

I don't personally know much about ECL, it's just the implementation available in Termux's package system. CLOG itself loads fine and I can run the demos. I did get it everything loaded and working on windows with SBCL, so it could be an implementation thing?

**Comment by rabbibotton** [comment]
I use sbcl on termux, it will work with ecl but depending on version of ecl
have to remove that reference etc

see https://github.com/rabbibotton/clog/blob/main/ANDROID-TERMUX.md

**Comment by rabbibotton** [comment]
Just to clarify more, apps made with CLOG work perfect with ecl, the issues is the builder project system (I am writing a new one since ecl dies on it and Windows is slow............) but in mean time (like week or two :) ) will need to use sbcl to run builder on termux.

**Comment by rabbibotton** [comment]
oh reason ECL dies is that recent versions of ecl use a custom version of ASDF

**Comment by argentcorvid** [comment]
Ok thanks for the clarification!

**Comment by rabbibotton** [comment]
the latest version in git and UltraLisp should load if you can confirm for  me also on ecl on termux.

**Comment by rabbibotton** [comment]
Interestingly enough the issue with ASDF/SYSTEM-REGISTRY is that it shows up in generated code despite not being in the original CLOG files. Interesting thing to keep an eye out for that the reader will replace symbols. Either way it should be ok. I have setup ecl on my termux as well it works well, maybe a bit better than sbcl. closing this

**Comment by argentcorvid** [comment]
Proof of life!

**Comment by argentcorvid** [comment]
Proof of life!

![Screenshot_20240421_141941_Firefox](https://github.com/rabbibotton/clog/assets/28569263/4b7b591a-3115-4b3a-98ee-76062408196b)

**Comment by rabbibotton** [comment]
Bet you never imagined you would have the most powerful dev system in the world running on the phone in your pocket :P 

get  you the IP of you phone and run the builder your computer too :)

**Comment by aykaramba** [comment]
I have  Librem 5 that I need to try and install CLOG on as well.
