### ISSUE TITLE
Tutorial 07: handling disconnects not working

### ISSUE THREAD

**Issue by hulufei** [rabbibotton/clog#349]
Hi, thanks for creating the awesome project.

I was trying to catch disconnect to do some clean up. I saw tutorial 07 mentioned handling disconnects, but after I run tutorial 07, when I close the browser, the "Lost connection" message didn't show up.

**Comment by rabbibotton** [comment]
That shows if the disconnect occurs abnormally. 
Add:

            (sleep .02)))
        (format t "Normal Disconnect~%"))
    (error (c)
      (format t "Lost connection.~%~%~A" c))))

Will see ends normally.

I added that to last commit.
