### ISSUE TITLE
Does not work with Slime version 2.30

### ISSUE THREAD

**Issue by andrej-ozi** [rabbibotton/clog#352]
I am using Spacemacs, which packages Slime 2.30 for Common Lisp. When I try to install Clog as per instructions I get constant hangups when SBCL gets to installing package swank/gray, and spits out `Evaluation aborted on #<UNDEFINED-FUNCTION NIL`.  I suspect this is because new version of Slime is incompatible with version of Swank shipped with Ultralisp.

I am however able to install and run Clog by running: `sbcl --eval '(ql:quickload :clog/tools)' --eval '(clog-tools:clog-builder)'`

**Comment by rabbibotton** [comment]
Breaks a whole lot more I saw this morning, that was a nasty curve

**Comment by rabbibotton** [comment]
btw thanks for the work around for CLOG going to modify instructions now

**Comment by sabracrolleton** [comment]
It is a problem for us emacs users as well. Clack insists on installing swank, even if we already have slime/swank installed. 

If you keep your emacs packages up to date, emacs is pulling slime version 2.30 (which is now three weeks old) and there have been several commits to slime since. 

If you use ultralisp, this results in clack trying to install a newer version of swank over the version which is currently running in emacs, resulting in bad things happening.  I ended up putting a static version of slime/swank in my local projects file so that ultralisp would stop trying to load the most recent version.

**Comment by Moriaty0o0** [comment]
> It is a problem for us emacs users as well. Clack insists on installing swank, even if we already have slime/swank installed.
> 
> If you keep your emacs packages up to date, emacs is pulling slime version 2.30 (which is now three weeks old) and there have been several commits to slime since.
> 
> If you use ultralisp, this results in clack trying to install a newer version of swank over the version which is currently running in emacs, resulting in bad things happening. I ended up putting a static version of slime/swank in my local projects file so that ultralisp would stop trying to load the most recent version.

yes,  i also met this  problem with emacs. the repl stucks with load package ```swank/gray```, but  it's ok with sbcl in cmd on windows.

**Comment by rabbibotton** [comment]
can either of you try the following is you are using ultra lisp - edit .quickslip/slime-helper.el

(unless (boundp 'quicklisp-slime-helper-dist)
  (setq quicklisp-slime-helper-dist "ultralisp"))

that will insure all using with ultralisp the lastest versions of all that should be compatible. I seem to have no issues with 2.30 and could be part of why I am not seeing it.

**Comment by sabracrolleton** [comment]
I live in emacs (mostly not involving common lisp) and it can be running as a daemon for weeks. I prefer having emacs control emacs. 

Assuming two weeks along I decide to load some CL package that wants to load clack and clack wants to load swank. Are you saying that changing slime-helper.el as suggested will prevent ultralisp from trying to load a newer version of swank over the top of a swank session that is already been running for two weeks?

**Comment by rabbibotton** [comment]
The issue is on new installs and during installation

**Comment by Moriaty0o0** [comment]
> can either of you try the following is you are using ultra lisp - edit .quickslip/slime-helper.el
> 
> (unless (boundp 'quicklisp-slime-helper-dist) (setq quicklisp-slime-helper-dist "ultralisp"))
> 
> that will insure all using with ultralisp the lastest versions of all that should be compatible. I seem to have no issues with 2.30 and could be part of why I am not seeing it.

everything is ok after modifying the slime-helper.el, thank you.
