### ISSUE TITLE
Feature request : Hot Reload / Live Reload

### ISSUE THREAD

**Issue by 0fflineuser** [rabbibotton/clog#354]
Hi,

I think they would be great for when developping, as it would eliminate the need to manually refresh the web page and allowing us to instantly see changes in the browser. 

Examples :
- [Flutter Hot Reload](https://www.youtube.com/watch?v=sgPQklGe2K8)
- [Live Reload](https://www.youtube.com/watch?v=QQ3J59AKZLU)

**Comment by rabbibotton** [comment]
Not sure why you would not do it in your code with (reload (location body))
or at a REPL (just set a global to current window while testing)?

**Comment by rabbibotton** [comment]
If you mean individual elements. same exact thing - just do it. CLOG is
always live. Maybe give me example as you may not have made the leap to a
CLOG brain yet :)

CLOG is the original hot load :)

(setf *t* (create-div body :content "hello")
(setf (text-value *t*) "Hello World!")

**Comment by rabbibotton** [comment]
In most cases you probably don't need to ever reload as you are writing an
App not a web page :) You will see :) That is part of the CL power you are
having a conversation with it, not writing a program.

**Comment by aykaramba** [comment]
Also, if you use Emacs or lem, you can just bind a key binding to call something like:

```
  (defun reload (obj)
    (url-replace (location body) "/"))
```

Here is my Lem binding: https://github.com/aykaramba/edgar/blob/main/commands.lisp

I load that up in my EDGAR project, it is Lem specific.  I need to write one for Emacs as well.

When I am coding in C-c all the time and when I want to see my chances updated in the browser I just C-v whenever I want.
