### ISSUE TITLE
CLOG not working on MS Windows 11 pro

### ISSUE THREAD

**Issue by fba00** [rabbibotton/clog#357]
Hello and thanks a lot for this fantastic package!
I used it on Win10pro with SBCL 2.4.4, it seems to work fine.
But I could not make it work win Win11pro. Hunchentoot triggers a BIND 10013 (when tested separately Hunchentoot works fine)
I tried to disable the firewall and all kinds of safety features, with no effect.
I would appreciate some help to try solving this mystery.
Thanks a lot in advance and best regards,

Frederic (fba00)

-----Here is the REPL command:-----------
(clog:run-demo 1)

 ---- The demo src is located at: C:/Users/fba/quicklisp/dists/ultralisp/software/rabbibotton-clog-20240512155434/./demos/01-demo.lisp
Hunchentoot server is started.
Listening on 0.0.0.0:8080.
HTTP listening on    : 0.0.0.0:8080
HTML root            : C:/Users/fba/quicklisp/dists/ultralisp/software/rabbibotton-clog-20240512155434/./static-files/
SSL                  : no
SSL Key File         : NIL
SSL Cert File        : NIL
Long poll first      : no
Boot function added  : no
Boot html source use : compiled version, when no file
Boot js source use   : compiled version
Boot file for path / : /boot.html
If browser does not start go to http://127.0.0.1:8080
#<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {1003081613}>

-----Error backtrace:-----------

Socket error in "bind": 10013 (Une tentative d’accès à un socket de manière interdite par ses autorisations d’accès a été tentée.)
   [Condition of type SB-BSD-SOCKETS:SOCKET-ERROR]

Restarts:
 0: [ABORT] abort thread (#<THREAD tid=8216 "clack-handler-hunchentoot" RUNNING {1002E29653}>)

Backtrace:
 0: (USOCKET:SOCKET-LISTEN "0.0.0.0" 8080 :REUSEADDRESS T :REUSE-ADDRESS NIL :BACKLOG 50 :ELEMENT-TYPE (UNSIGNED-BYTE 8))
 1: ((:METHOD HUNCHENTOOT:START-LISTENING (HUNCHENTOOT:ACCEPTOR)) #<CLACK.HANDLER.HUNCHENTOOT::CLACK-ACCEPTOR (host 0.0.0.0, port 8080)>) [fast-method]
 2: ((SB-PCL::EMF HUNCHENTOOT:START-LISTENING) #<unused argument> #<unused argument> #<CLACK.HANDLER.HUNCHENTOOT::CLACK-ACCEPTOR (host 0.0.0.0, port 8080)>)
 3: ((:METHOD HUNCHENTOOT:START (HUNCHENTOOT:ACCEPTOR)) #<CLACK.HANDLER.HUNCHENTOOT::CLACK-ACCEPTOR (host 0.0.0.0, port 8080)>) [fast-method]
 4: (CLACK.HANDLER.HUNCHENTOOT:RUN #<FUNCTION (LAMBDA (LACK/MIDDLEWARE/BACKTRACE::ENV) :IN "C:/Users/fba/quicklisp/dists/ultralisp/software/fukamachi-lack-20240209100541/src/middleware/backtrace.lisp") {1..
 5: ((FLET BT2::RUN-FUNCTION :IN BT2::ESTABLISH-DYNAMIC-ENV))
 6: ((LABELS BT2::%ESTABLISH-DYNAMIC-ENV-WRAPPER :IN BT2::ESTABLISH-DYNAMIC-ENV))
 7: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 8: ((FLET "WITHOUT-INTERRUPTS-BODY-" :IN SB-THREAD::RUN))
 9: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-" :IN SB-THREAD::RUN))
11: (SB-THREAD::RUN)

**Comment by rabbibotton** [comment]
That error generally occurs when something is already running on the port you are trying to use. Try changing starting the demo on another port. So for example change in tutorial 1 -  (initialize #'on-new-window :port 8081) and see if works. Let me know.

**Comment by rabbibotton** [comment]
In genera if you use :port 0 - CLOG picks a port not being used to make sure this does not happen.

**Comment by fba00** [comment]
Thanks for your fast and efficient diagnosis! Indeed, 8080 was already used. 
Just killing the process and then CLOG works fine.
In my case MiniTool ShadowMaker was blocking 8080, nothing to do with Win11: I did just not install ShadowMaker on my Win10 config, that's all. Sorry for the misleading issue name.
Best regards!

**Comment by rabbibotton** [comment]
May the CLOG be with you :)

**Comment by fba00** [comment]
Thanks again! I renamed the issue (as the name was misleading, nothing to do with Win10/Win11) and closed it!

Best regards!

Frederic

----- Mail original -----
De: "David Botton" ***@***.***>
À: "rabbibotton/clog" ***@***.***>
Cc: "fba00" ***@***.***>, "Author" ***@***.***>
Envoyé: Lundi 27 Mai 2024 16:32:27
Objet: Re: [rabbibotton/clog] CLOG not working on MS Windows 11 pro (Issue #357)





That error generally occurs when something is already running on the port you are trying to use. Try changing starting the demo on another port. So for example change in tutorial 1 - (initialize #'on-new-window :port 8081) and see if works. Let me know.
