### ISSUE TITLE
Strange behaviour in UI dropdown menu

### ISSUE THREAD

**Issue by Diogenesoftoronto** [rabbibotton/clog#369]
I have tried this within the firefox browser version using 127.0

It is difficult to describe this in words but the dropdown menu seems to switch to the last menu option whenever I hover over it. This effect takes place whether I click the menu or not and stops once I no longer hover over the menu. The video contains a better demonstration than what I can describe. 

[Screencast from 2024-06-24 09:00:05 PM.webm](https://github.com/rabbibotton/clog/assets/87236699/d40b6f0d-9e8c-4259-b68b-bf31be4620a8)

**Comment by rabbibotton** [comment]
It is refreshing the contents. The builder can span many web pages that can close down with out warning etc. at least for now was a solution. Already have better answers before CLOG 3 in mind.
