### ISSUE TITLE
Incorporate in existing web server 

### ISSUE THREAD

**Issue by vajrabisj** [rabbibotton/clog#371]
Is it possible to incorporate clog into existing web server, ie for certain routes to use clog. Thanks.

**Comment by rabbibotton** [comment]
The answer is yes depending on your server. WEBSERVER.md for how to do with Apache and reverse proxy.

Another way (imo best way) is to serve all your static html etc from your current webserver including the boot.js file which you modify to a different port to access you CLOG's websocket server. Note: For security the websocket protocol must still be on same domain.

Line 91 in boot.js =
```
  if (location.port != '') { adr = adr + ':' + location.port; }
```

You would just change for example the port to 8888
```
  adr = adr + ':8888';
```

**Comment by vajrabisj** [comment]
Thanks for your reply. It seems i still cannot get that. I need to setup one of my router, eg example.com:5050/clog to be rendered by clog, and other routers need to still process by webserver which is serving on port 5050. How can i setup CLOG? just changing the ws port as you suggested seems not working...

**Comment by rabbibotton** [comment]
if has to be same port - 5050 you will need to configure your webserver (unless is also using CLACK) to proxy clog. If can move /clog to 5051 then modifying the boot.js file to use 5051 and serving boot.html from the 5050 server should work no issue.

**Comment by rabbibotton** [comment]
Feel free to give me details, configs and code to better help

**Comment by rabbibotton** [comment]
let me know in the end if this works

**Comment by vajrabisj** [comment]
Thanks. I changed port in boot.js as you suggested and encountered problem
to show the page on /clog route. It seems I did not properly setup the path
to the boot.html. There are many arguments in the function clog:initialize,
should I modify some of them to use boot.js and serve the boot.html file?

/clog is on 5050, and boot.js port is 8080. Page not shown on
server.com:5050/clog, but it is shown on server.com:8080/





Regards,

Michael


David Botton ***@***.***>于2024年6月30日 周日22:47写道：
