### ISSUE TITLE
Windows quick installer never completes

### ISSUE THREAD

**Issue by Masciguy** [rabbibotton/clog#372]
I am using the "CLOG Builder EZ Install v1.2 for Win 64" and after running setup.bat the process seems to freeze at 'Loading "cl-isaac"' No builder.exe file is created as the bat file doesn't finish running. I tried running the update.bat file and this freezes at the same point.

**Comment by rabbibotton** [comment]
are you behind a proxy? i.e. not able to download the files

**Comment by Masciguy** [comment]
I apparently just didn't wait long enough, it finally started finished. Maybe some way to indicate it is actually doing something and not frozen would be handy, but not necessary.
