### ISSUE TITLE
CLOG crashes my Firefox when I add alert to 18-tutorial.lisp :(

### ISSUE THREAD

**Issue by svetlyak40wt** [rabbibotton/clog#380]
I tried to change a code of 18 tutorial just to see how it will process `set-on-drag-over` if there will be non empty lambda.

Here is the code I've replaced empty lambda with:

```
(set-on-drag-over target2 (lambda (obj)                                                                                                   
                               	(alert (window body) "SOME ALERT")))
```

With this change, if I drag green box to the right yellow box, browser first shows the alert and then crashes.

**Comment by rabbibotton** [comment]
CLOG crashing a browser is impressive.. What version of firefox?

Will try it myself as soon as I can.

**Comment by rabbibotton** [comment]
Sorry I have been so absorbed in a work project I didn't ask how you are? I hope amazing and been wishing you health and more. Your work is precious for us all

**Comment by rabbibotton** [comment]
Sorry for long delay. So the alert function is a nasty one - it actually should never be used with clog. It freezes web-sockets and the entire javascript system. You can use the clog-web or clog-gui alerts and toasts if can.
