### ISSUE TITLE
clog-connection-websockets.lisp function 'initialize', should lack package qualified symbols use "." instead of "/"?

### ISSUE THREAD

**Issue by monkpearman** [rabbibotton/clog#383]
In file source/clog-connection-websockets.lisp
The function 'initialize' has the following form:

```lisp
 (cond ((and (eq static-boot-js nil)
             (equalp path "/js/boot.js"))
        `(200 (:content-type "text/javascript")
              (,*compiled-boot-js*)))
       ((ppcre:scan "^(?:/clog$)" path)
        (clog-server env))
       ((plugin-path path)
        ;; (lack/middleware/static::call-app-file (plugin-path path) env))
        (lack.middleware.static::call-app-file (plugin-path path) env))
       (t
        ;; (lack/middleware/static::call-app-file *static-root* env)
        (lack.middleware.static::call-app-file *static-root* env)))
```

I can not get current version of Clog from git as of 2024-09-16 current thru
commit 4a35cab to build on SBCL 2.4.6, unless i change the following package qualified symbols to use
"." instead of "/".  Note, I am building Clog with quicklisp WITHOUT the Ultralisp dist registered.

Upon further inspection, it seems that following Nov 8, 2023 commit from lack [Change names of packages to slash-separated ones.](https://github.com/fukamachi/lack/commit/8243010b48a10edd527da4e94686b803c70731ef)
introduced the slashified package qualified symbols.

**Comment by rabbibotton** [comment]
I use sbcl 2.4.7 every day for projects with clog, so it is not related to sbcl. Do you have copy of ASDF someplace in your common-lisp or projects? (not saying I won't see about changing to '.' but want to understand your issue and why lack changed first.

**Comment by monkpearman** [comment]
I don't think anything substantive changed other than lack changed
it's package qualified name from: lack.middleware.static:foo to 
lack/middleware/static:foo

i was running an older version of lack from most recent QL dist release as opposed to from Ultralisp. feel free to mark this closed.  No one else will encounter the build error i did if they are using up to date systems from Ultralisp.  The good news is Clog from git repo still builds from last yeats QL dist with minimal changes 😁

**Comment by rabbibotton** [comment]
:)
