### ISSUE TITLE
CLOG depends on trivial-open-browser but doesn't use it

### ISSUE THREAD

**Issue by khinsen** [rabbibotton/clog#388]
There is a declared dependency on `trivial-open-browser` in `clog.asd`, but CLOG has its own `open-browser` function in `source/clog-system.lisp`, and doesn't use `trivial-open-browser` at all.

Two possible improvements:
 - Remove the dependency on `trivial-open-browser`
 - Remove CLOG's `open-browser` and import the same-named function from `trivial-open-browser`.

I'd be happy to submit a patch for either one.

**Comment by rabbibotton** [comment]
trivial-open-browser is a bit broken so better to remove dep. a patch would be perfect :)
