### ISSUE TITLE
Looking for someone to write a common-lisp tutorial in CLOG

### ISSUE THREAD

**Issue by rabbibotton** [rabbibotton/clog#4]
Since CLOG is interactive and live it is an amazing platform to teach Common Lisp. I am looking for someone interested in writing a CLOG program to teach Common Lisp! If interested please let me know, I am willing to help!

**Comment by jkordani** [comment]
I'm curious to see how to use this to live code a site.  So far I'm not sure exactly how to redefine a function in the repl and have the results be reflected in the browser without having to issue a page refresh

**Comment by rabbibotton** [comment]
Hmm, I should make some sort of REPL tricks doc. I'll try and do soon as the for sure would help many during dev and for sure is part of why I am loving common-lisp. I'll write back soon!

**Comment by rabbibotton** [comment]
I have added to the docs REPL instructions.
https://rabbibotton.github.io/clog/clog-manual.html#x-28CLOG-3A-40CLOG-PROGRAMMING-BASICS-20MGL-PAX-3ASECTION-29
