### ISSUE TITLE
Tutorial 6

### ISSUE THREAD

**Issue by tmccary9207** [rabbibotton/clog#47]
Hello, Thank you so much for creating this very interesting piece of technology. I was running tutorial 6 and when I clicked the second time to stop it the console printed the start message once followed by two stop messages. I am running on Ubuntu 20 with an Intel processor and using the firefox browser. I am wondering if there is any minimum requirements I am not meeting that could be causing the double printing or if it is running as designed.

**Comment by mavis-risetti** [comment]
Did that happen just one time?
Or is it consistently doing that?

**Comment by rabbibotton** [comment]
The goal of the tutorial was to show that each event (click in this case) creates a thread, so clicking to start the flash and clicking again to stop it should produce:

"Event thread started" 
"Event thread started" 
"Event thread stopped" 
"Event thread stopped"
