### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [rabbibotton/clog#49]
Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id a884327fc1c41c0baa18e68bfb7d98effee572ed

*clog* fails to build with the following error:

```
; caught WARNING:
;   Literal string as destination in FORMAT:
;     (FORMAT "~(~a~)Storage.length" STORAGE-TYPE)
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A10083}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "clog" "clog-window">

```

*clog/tools* fails to build because of a failure in  _clog_.

*hello-clog* fails to build because of a failure in  _clog_.

[Full log here](http://report.quicklisp.org/2021-03-16/failure-report/clog.html)

**Comment by rabbibotton** [comment]
Corrected in commit c2ec52d
