### ISSUE TITLE
Opening Emacs in clog directory, still page "not found"

### ISSUE THREAD

**Issue by jacksonbenete** [rabbibotton/clog#5]
Hello there,
I'm trying to take a look at CLOG.
I've started Emacs on clog directory under `~/common-lisp/` just like the tutorial asks.
Starting the tutorial still shows "Not Found" though.

```
SBCL 2.0.1.debian.
GNU Emacs 27.1
Slime 2.26
quicklisp 2020-10-16
```

![Screenshot from 2021-01-22 21-51-00](https://user-images.githubusercontent.com/2954722/105563448-da5d6580-5cfc-11eb-956d-b0920a27ca72.png)

![Screenshot from 2021-01-22 21-51-10](https://user-images.githubusercontent.com/2954722/105563452-de898300-5cfc-11eb-8f7b-195f6719695a.png)

![Screenshot from 2021-01-22 21-51-13](https://user-images.githubusercontent.com/2954722/105563455-e21d0a00-5cfc-11eb-9570-df16f1e7c30b.png)

**Comment by rabbibotton** [comment]
Try using:

**Comment by rabbibotton** [comment]
Try using someting like this - (setf clog::*overide-static-root* #P"~/common-lisp/clog/static-files/") let me know if that works.

**Comment by rabbibotton** [comment]
CLOG now finds itself in lates git so no need to use any work arounds.

**Comment by jacksonbenete** [comment]
Thanks @rabbibotton . Sorry for the late reply.
The workaround `(setf clog::overide-static-root #P"~/common-lisp/clog/static-files/")` didn't worked, but updating clog and cloning the new version did worked.
