### ISSUE TITLE
(create-form-element form :select) does not work

### ISSUE THREAD

**Issue by engblom** [rabbibotton/clog#59]
(create-form-element form :select) does not work. As all kind of form elements can be used with (create-form-element ...) it would be logical to also have :select as an option.

**Comment by rabbibotton** [comment]
That is correct as select is not considered by html to be an "input" type. It is true that I could still "force" it by coding things as such but the clog-select object has additional methods. Do you have a specific use-case for that?

**Comment by engblom** [comment]
No, I do not have a special use case requiring it, I just thought that for consistency it could be good as then all form elements could be added in the very same way.

**Comment by rabbibotton** [comment]
Let me think about it, in truth with CL I can return different types of objects with same method, so reasonable. If I do I will do post 1.0 in next month. Thanks!
