### ISSUE TITLE
How to query DOM?

### ISSUE THREAD

**Issue by bmansurov** [rabbibotton/clog#68]
Say, I created a bunch of form elements with `create-form-element` but didn't keep references. How can I get references to those elements? In jQuery I may do something like `$('form').find('input')`. Is it possible with CLOG? Thanks.

**Comment by smvamse** [comment]
No. You can't query using CSS selectors like id, classes, or tag names. You should hold references to all the elements you've created - if you want to use them again.
But, you can execute js using `js-query` or `js-execute`.

**Comment by bmansurov** [comment]
OK, thanks!
