### ISSUE TITLE
 Symbol "UPDATE-ASDF-SYSTEM-HTML-DOCS" not found in the MGL-PAX package.

### ISSUE THREAD

**Issue by nvseok** [rabbibotton/clog#69]
Whilst quickloading clog:  

[package clog-user]
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "UPDATE-ASDF-SYSTEM-HTML-DOCS" not found in the MGL-PAX package.
;   
;       Line: 130, Column: 39, File-Position: 3763

in the clog-helpers.lisp file
Running on Windows, portacle SBCL

**Comment by nvseok** [comment]
I've commented out that line for now, and it loads successfully

**Comment by rabbibotton** [comment]
You need to install MGL-PAX
