### ISSUE TITLE
demo 1 fail, demo 2 ok with warnings, manual ok

### ISSUE THREAD

**Issue by Devon7** [rabbibotton/clog#9]
```
$ git clone https://github.com/rabbibotton/clog.git
⋮
(ql:update-all-dists)
(ql:quickload "clog")
(clog-user:run-demo 1)	; error no such external symbol
(clog-user::run-demo 1)
⋮
;   In START-GAME: Unused lexical variable BR
⋮
New connection id - 1 - #<SERVER #x3020B18785BD>
[2021-02-01 13:09:15 [ERROR]] Error while processing connection: The condition on #<BASIC-TCP-STREAM ISO-8859-1 (SOCKET/31) #x3020B143B96D> : 
Broken pipe (error #32) during write occurred with errno: 0.
⋮
The value NIL, derived from the initform NIL, can not be used to set the value of the slot CLOG-USER::SNAKE in #<CLOG-USER::APP-DATA #x3020B1A1D1BD>, because it is not of type CONS.
   [Condition of type CCL::BAD-SLOT-TYPE-FROM-INITFORM]
  0: (CCL::%SHARED-INITIALIZE #<CLOG-USER::APP-DATA #x3020B1A1D1BD> T NIL)
      Locals:
        INSTANCE = #<CLOG-USER::APP-DATA #x3020B1A1D1BD>
        SLOT-NAMES = T
        INITARGS = NIL
        WRAPPER = #<CCL::CLASS-WRAPPER CLOG-USER::APP-DATA #x3020B0679E1D>
        CLASS = #<STANDARD-CLASS CLOG-USER::APP-DATA>
        #:G135927 = (#<STANDARD-EFFECTIVE-SLOT-DEFINITION for instance slot CLOG-USER::SNAKE #x3020B0679FAD>)
        SLOTD = #<STANDARD-EFFECTIVE-SLOT-DEFINITION for instance slot CLOG-USER::SNAKE #x3020B0679FAD>
        PREDICATE = CONSP
        IGNORE = NIL
        NEW-VALUE = NIL
        FOUNDP = NIL
        INITFUNCTION = #<Compiled-function FALSE #x300000085B4F>
        NEWVAL = NIL

```

(clog-user::run-demo 2) ; chat works despite minor warnings.
;   In an anonymous lambda form inside SEND-MESSAGE: Unused lexical variable KEY
;   In an anonymous lambda form inside ON-NEW-WINDOW: Unused lexical variable OBJ
;   In ON-NEW-WINDOW: Unused lexical variable TMP (4 references)
;   In ON-NEW-WINDOW: Unused lexical variable CAPTION

(clog:open-manual) ; manual browser works with no warnings.

**Comment by rabbibotton** [comment]
It looks like your system is mixing up symbols with the quicklisp version of clog and the git version. Make sure you restart your lisp so no symbols around from a previous build for clog. Run  (ql:quickload :clog) then (clog:clog-install-dir) and that will tell you which is running. If that symbol is undefined you are using the quicklisp version. Also which lisp are you using?

**Comment by rabbibotton** [comment]
I pushed a number of fixes to style warnings and other warnings.

**Comment by Devon7** [comment]
$ git pull
$ ccl
CL-USER> (ql:quickload "clog")
CL-USER> (clog-user:run-demo 1)
CL-USER> (clog:clog-install-dir)
~/quicklisp/local-projects/clog/

**Comment by rabbibotton** [comment]
I will see if can find a machine with ccl to test. Latest code same issue?

**Comment by Devon7** [comment]
Fixed a typo
[clog.patch.txt](https://github.com/rabbibotton/clog/files/5909382/clog.patch.txt)

**Comment by rabbibotton** [comment]
Applied patch thanks! I also removed the types on the app-data for now so should compile with CCL. When I have time to setup my wife's machine with CCL and see where issue is (sbcl is ok with the types)

**Comment by Devon7** [comment]
(clog:run-demo 1) ; snake game works
(clog:run-tutorial 1) ; tutorial works
however, when I close the tutorial tab,
causing the snake game tab to appear,
redisplay gets the tutorial instead of the game.

**Comment by rabbibotton** [comment]
I am thinking to change the demos and tutorials to each have a different URL path so that they can run simultaneous but since they currently all use the root path '/' that would be expected. Ok happy all working now. I'll try and set up ccl soon for testing also, but please let me know if anything else comes up.
