### ISSUE TITLE
Wrong reaction on :html-id 0

### ISSUE THREAD

**Issue by 3vau** [rabbibotton/clog#94]
Hello! I have discovered a new problem of my favorite clog😂
When I ordered a clog-element as `:html-id 0`, all operation on it will certainly redirect to `<body>`... It's difficult to say but it can be easily produced by add `:html-id 0` to the 70 line of 08-tutorial, change it to `(let* ((div1 (create-div body :html-id 0))`.
It is a little problem, but I hope it will do some help. :D
![image](https://user-images.githubusercontent.com/58899952/146662458-d890cfb8-59d3-465a-8616-10012ebccfb0.png)

**Comment by rabbibotton** [comment]
In general I wouldn't use :html-id but if have a need (want to make the div easily available to JS) I would use some unique name not a number that may get it confused internally. I will see about documentation to not use a number as a custom html-id unless prefixed by at least one character.

**Comment by 3vau** [comment]
> In general I wouldn't use :html-id but if have a need (want to make the div easily available to JS) I would use some unique name not a number that may get it confused internally. I will see about documentation to not use a number as a custom html-id unless prefixed by at least one character.

Thank you! I will try to use another way! 😆
