### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by j3pic** [rabbibotton/clog#95]
I got this message when I tried to load CLOG:

```
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "UPDATE-ASDF-SYSTEM-HTML-DOCS" not found in the MGL-PAX package.
;   
;       Line: 151, Column: 39, File-Position: 4380
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /tmp/clog/source/clog-helpers.lisp" {1006D42433}>
```

That error falls in this function:

```common-lisp
(defun make-html ()
  (load-world)
  (mgl-pax:update-asdf-system-html-docs clog:@CLOG-MANUAL :clog))
```

I tried replacing it with this:

```common-lisp
(defun make-html ()
  (load-world)
  (error "Not implemented"))
```

Then it compiled and worked with no problems. All dependencies were whatever versions Quicklisp is serving right now.

**Comment by rabbibotton** [comment]
It is a misconfiguration on your machine. What is your setup? Also make sure to update quicklisp - (ql:update-dist "quicklisp")

**Comment by rabbibotton** [comment]
The latest in github moves out the documentation functions to its own asdf subsystem (ql:quickload :clog/docs) (clog:make-html) 

This will remove your issue, but as I have seen with one or two others worth compartmentalizing the issue since I am likely the only one to run those functions.

Let me now how it goes for you.

**Comment by rse3vau** [comment]
I met the same error just now on macOS 10.15 with SBCL 2.2.7, and I attempt to clone [mgl-pax](https://github.com/melisgl/mgl-pax) to my ~/common-lisp manually and the problem have been solved :D

Put here for anyone who got the same problem.
