### ISSUE TITLE
Manual out of sync

### ISSUE THREAD

**Issue by chuchana** [rabbibotton/clog#96]
First of all: thank you for this system!

Near the beginning of the manual, I noticed that its text doesn't match the current code.

It says
```
CL-USER> (load "path to clog/demos/01-snake.lisp")
CL-USER> (clog-user:start-demo)
```
while I had to run
```
(load "path to clog/demos/01-demo.lisp")
(clog-demo-1:start-demo)
```

I assume that at least for the file name what the manual says should be correct because it is more telling, but for `start-demo`, I'm not sure because one could load more than one demo. Maybe something like `(clog-user:start-demo N)` would make sense if more than one is loaded?

**Comment by rabbibotton** [comment]
Thank you for pointing that out!! I have updated it.
