### ISSUE TITLE
Windows WSL information in README.md may be incomplete/may need improvement

### ISSUE THREAD

**Issue by mustiboost** [rabbibotton/clog#97]
In the README.md file it says: "Tip for Windows WSL linux user. Create a symbolic link from wslview to xdg-open in /usr/local/bin so that run-tutorial uses the windows browser."

I don't know about WSL1 but in WSL2 (using Ubuntu)  you do not need to create a symbolic link. What you *do* need to do in that case, though, is to install the "xdg-utils" package with `sudo apt install xdg-utils`, so xdg-open is available, as xdg-open is not installed by default. After that Microsoft Edge (my default) pops up when I run `(clog:run-tutorial 1)` .  I think eliminating the symbolic link part may make it easier to understand how to run clog for beginners than having to deal with symbolic links (as easy as it is).

**Comment by rabbibotton** [comment]
I have made your suggested change. Thanks!
