### ISSUE TITLE
 installing clog using portacle on Linux is failing

### ISSUE THREAD

**Issue by EarwainBanadar** [rabbibotton/clog#98]
Hello,

I'm not able to install clog using portacle on Linux:

CL-USER> (ql:quickload :clog)
; Evaluation aborted on #<QUICKLISP-CLIENT:SYSTEM-NOT-FOUND {100A461433}>.

are there any hints to solve this issue?

Beside of this quicklisp is working properly, e.g. (ql:quickload "mcclim") is working properly.

Best

**Comment by rabbibotton** [comment]
You are likely running an old distribution of QuickLisp
 (ql:update-dist "quicklisp")

or you can do the latest github
cd ~/common-lisp
git clone https://github.com/rabbibotton/clog.git

Let me know if that solves your issue, thanks!

**Comment by EarwainBanadar** [comment]
Thank You very much. 
Your hint solved this problem.
I'm very exited to have a look at your solution!
