### ISSUE TITLE
Opening gui_builder - browser content is mangled

### ISSUE THREAD

**Issue by EarwainBanadar** [rabbibotton/clog#99]
Hello RabbiBotton,

I do have the following issue as the situation is al follows:

- Ubuntu 20.10
- Firefox Webbrowser as default
- The Browser is closed
- running (clog-tools:clog-builder)
- Firefox will open, but the content/text is mangled (look at atatched image).
![clog_mangled](https://user-images.githubusercontent.com/64350838/150314641-d60c4e8b-70ff-4808-b07f-e8c5aa6b67bf.JPG)

But if firefox is already open, a new tab will open and the content will be displayed properly:
![clog_correct](https://user-images.githubusercontent.com/64350838/150316219-b82a682f-eab3-4c11-84ad-fe23d6979aaf.JPG)

The Firefox version is as followin
![firefox_ubuntu](https://user-images.githubusercontent.com/64350838/150316331-270ad965-f6da-474a-a192-1b7c5dd25fb6.JPG)
:

**Comment by rabbibotton** [comment]
Strange. I have not tested extensively with FF but I will add it to my rotation and see what is going on.

**Comment by rabbibotton** [comment]
I could not reproduce this on FireFox 96.0.1 on Ubuntu 21.1
So it seems to not be related to Clog on SBCL or ECL
If you notice it on other systems in future let me know.
